### ISSUE TITLE
LC0005 - false positive on array datatype

### ISSUE THREAD

**Issue by ChristianHovenbitzer** [StefanMaron/BusinessCentral.LinterCop#102]
I get a warning about casing for array variables. I expect "array" to not trigger a warning while "Array" should.

![image](https://user-images.githubusercontent.com/91181840/143218267-f8897332-495e-41d8-b91b-207610bf7f25.png)
![image](https://user-images.githubusercontent.com/91181840/143218312-43fdf73f-24df-471f-95b7-a68265f50bc7.png)

**Comment by nickgoddard777** [comment]
Yeah, I'm getting this too.

![image](https://user-images.githubusercontent.com/332366/143272109-5c9cdb63-8d62-489d-a6b2-333706d8460d.png)

**Comment by rvanbekkum** [comment]
Also getting this false positive a lot.

**Comment by StefanMaron** [comment]
Available in pre-release v0.21.9

**Comment by nickgoddard777** [comment]
@StefanMaron That is now working for me, thanks :)
