### ISSUE TITLE
LC0003 Warning will be shown on correct line

### ISSUE THREAD

**Issue by someC0d3r** [StefanMaron/BusinessCentral.LinterCop#124]
Page Definition

```
page 50100 "Some Table List"
{
    SourceTable = "Some Table";
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    AccessByPermission = tabledata Item = R;
}
```

Warning shown:
`Do not use an Object ID for properties or variables declaration. Use tabledata Item = R instead.`

In VS Code:
![image](https://user-images.githubusercontent.com/88825803/148512776-07927f17-377c-481f-a474-c7e882c7a569.png)

Tested on release version: v0.23.0 (https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.23.0)

**Comment by StefanMaron** [comment]
I can not reproduce that. Could you create a simple demo project where this can be reproduced?

**Comment by someC0d3r** [comment]
Mea culpa
I reloaded the latest release and used it in my sample project, now it is working. Sorry. :/

Issue will be closed

![image](https://user-images.githubusercontent.com/88825803/149286296-1157f2c9-7650-4b36-9239-926c1eff9e8d.png)
