### ISSUE TITLE
LC0015 False positives on temporary tables

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#126]
LC0015 warns on tables with `TableType = Temporary`.

A user does not need permissions to write or read data in temporary tables, so I believe that LC0015 should skip the warning if there are no PermissionSet with TableData for that table.

The PTE0004 rule works in that way already.

**Comment by StefanMaron** [comment]
When #127 is implemented, this behavior will be correct, as table permissions are also needed for code on temp tables

**Comment by jwikman** [comment]
This now have the expected behavior, thanks to #127
