### ISSUE TITLE
[LC0005] two False positives

### ISSUE THREAD

**Issue by sschuh** [StefanMaron/BusinessCentral.LinterCop#129]
No. 1:
![bug2](https://user-images.githubusercontent.com/34685182/149732783-3e0356ac-7760-4662-a2dd-478e6d8bf9aa.png)

No. 2:
![bug1](https://user-images.githubusercontent.com/34685182/149733130-fd9b45ad-a11f-46d1-9a5f-1048fa1711a4.png)

**Comment by StefanMaron** [comment]
I tested it and I can not reproduce those errors
