### ISSUE TITLE
[LC0003] one False positives

### ISSUE THREAD

**Issue by sschuh** [StefanMaron/BusinessCentral.LinterCop#130]
![bug1](https://user-images.githubusercontent.com/34685182/149734543-f71961c0-4423-4132-be38-caa5e3f0627e.png)

**Comment by StefanMaron** [comment]
Should be fixed in the latest prerelease

**Comment by StefanMaron** [comment]
It seems to still warn on this pattern in local variables

**Comment by fvet** [comment]
@StefanMaron Has this been fixed in the latest release?

Still get a similar warning on code below

![image](https://user-images.githubusercontent.com/25268332/153209245-9de323c7-8c8f-4f4c-a6ed-3ab3180c7333.png)

**Comment by StefanMaron** [comment]
Yes it should be fixed. But apparently only for parameters and not for local variables. I will look into this

**Comment by StefanMaron** [comment]
Can you please confirm is this is fixed now? @fvet

**Comment by fvet** [comment]
I no longer get the warning. Thx for the fix !
