### ISSUE TITLE
[LC0016] False positive on system parts

### ISSUE THREAD

**Issue by invalidCards** [StefanMaron/BusinessCentral.LinterCop#148]
The newly introduced rule gives a warning of a missing caption on system parts, such as Links, while I'm pretty sure those are already added by the application. Manually-added normal page parts such as factboxes are properly detected by the rule.

**Comment by StefanMaron** [comment]
Should be fixed in [v0.24.2](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.24.2)

**Comment by invalidCards** [comment]
Can confirm. Thank you for the quick fix!
