### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by MJECloud** [StefanMaron/BusinessCentral.LinterCop#171]
Hey Stefan, 

since I can't find any license information in this repository I'm wondering if using your code is allowed. Could you please decide on a license and add it?

Thank you very much. 😊

**Comment by StefanMaron** [comment]
Thanks for pointing this out. The license it MIT.
I added it already to the prerelease branch which will be merged to master soon.
https://github.com/StefanMaron/BusinessCentral.LinterCop/blob/prerelease/LICENSE.md

If you create your own analyzer feel free to get inspired :)
It would be nice if you would create PR if you write a rule that could be useful for others as well!
