### ISSUE TITLE
LC0016 - not needed for data audit fields

### ISSUE THREAD

**Issue by NKarolak** [StefanMaron/BusinessCentral.LinterCop#178]
The [data audit fields](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-table-system-fields#audit) **SystemCreatedAt** and **SystemModifiedAt** added to pages or page extensions do not require a caption, because they are provided by the core application. Example in a German database:

In a page:
```AL
                field(Custom_SystemCreatedAt; Rec.SystemCreatedAt)
                {
                    ApplicationArea = All;                  
                    ToolTip = 'Specifies the date and time when the record was created.';
                }
```
Result in web client:
![image](https://user-images.githubusercontent.com/34504100/158170356-cdbb5a2e-f689-4c65-9732-9fe7cdaf9895.png)

**Comment by StefanMaron** [comment]
Should be fixed in https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.24.8

**Comment by NKarolak** [comment]
Confirmed, thank you :-)
