### ISSUE TITLE
LC0000 on array

### ISSUE THREAD

**Issue by NKarolak** [StefanMaron/BusinessCentral.LinterCop#179]
LC0000 is reproducible in this code (removed code for simplification; please don't judge the content ;-))

```AL
    local procedure Test(SubmissionNo: Code[10]; var Prefix: Text; var NumberTxt: Text; ErrorTxt: Text)
    var
        i: Integer;
    begin
        i := 1;
        Prefix[i] += SubmissionNo[i]; // LC0000
    end;
```

It's good the LC0000 pointed me to the marked. Correct would be actually:
`Prefix += SubmissionNo[i];`
However, AL does support my version above, and it returns the correct value, even in a loop. Hence, the line should not break your extension :-)

**Comment by NKarolak** [comment]
> Does the message say, which rule crashed?

Yes, sorry that I forgot: 
`There was an Error in Rule "Rule0017" of type "InvalidCastException" at Line 62`

**Comment by NKarolak** [comment]
This seems to be related with:
https://github.com/microsoft/AL/issues/6963

**Comment by StefanMaron** [comment]
Should be fixed in https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.24.8

**Comment by NKarolak** [comment]
Confirmed, thank you :-)
