### ISSUE TITLE
Microsoft.Dynamics.Nav.CodeAnalysis Reference

### ISSUE THREAD

**Issue by jcoe-nvt** [StefanMaron/BusinessCentral.LinterCop#180]
We're trying to enable LinterCop inside our pipelines. We use AlOps for most of our buildsteps.
The compile step automatically selects/downloads the latest VSIX (corresponding to the provided artifactversion) from the bcartifacts.cache folder.
In our case we are using artifactversion 19.1 and thus ALOps uses VSIX from C:\bcartifacts.cache\sandbox\19.1.31886.37487.

I tried adding the latest version of LinterCop to the Analyzers subfolder. But on compilation I get following errors:
`##[warning]warning AL1003: An instance of analyzer BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable cannot be created from C:\DockerInstallation\Agent\_work\189\s\BusinessCentral.LinterCop.dll : Could not load file or assembly 'Microsoft.Dynamics.Nav.CodeAnalysis, Version=8.2.8.39170, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
....
`

It seems that LinterCop requires a fixed version of Microsoft.Dynamics.Nav.CodeAnalysis. Is this really necessary to have this fixed reference? And if so, can we find a way to download a LinterCop version that works with the version of that VSIX?

**Comment by StefanMaron** [comment]
You need to use the latest version from the marketplace. 
You can use bc-containerhelper for that `Get-LatestAlLanguageExtensionUrl`

**Comment by StefanMaron** [comment]
I will release a new version compiled against the lasted vsix in a moment.
For now I do not have an automated way to always stay on the latest version

**Comment by StefanMaron** [comment]
Powerautomate to the rescue. 
Automatic check for a new vsix version on a daily basis is now in place. 
I will get a notification via mail and the build is triggered automatically

**Comment by jcoe-nvt** [comment]
Thank you for the update and automated compilation against latest vsix!
