### ISSUE TITLE
[LC0005] Does not trigger on global objects

### ISSUE THREAD

**Issue by invalidCards** [StefanMaron/BusinessCentral.LinterCop#188]
The wrong casing correctly detects when things like `Codeunit::X` and `Page::X` are incorrectly capitalised, but this doesn't seem to work when they are used as objects instead of enums (for example, when the `.Run()` function is called on those objects).

For example:
* `Codeunit.Run(Codeunit::X)` - correct casing, correctly no warning
* `Codeunit.Run(CODEUNIT::X)` - incorrect casing on the parameter, correctly shows warning
* `CODEUNIT.Run(Codeunit::X)` - incorrect casing on the "variable", **but no warning**

**Comment by Arthurvdv** [comment]
Thank you reporting this and should now be resolved in the release version of [v0.30.20](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.20) of the LinterCop.
