### ISSUE TITLE
[LC0016] Caption is missing on page of Type API

### ISSUE THREAD

**Issue by Arthurvdv** [StefanMaron/BusinessCentral.LinterCop#190]
![image](https://user-images.githubusercontent.com/44637996/160991526-5f483df0-857e-4dfe-aef9-2ed0b2eeafb2.png)

The warning LC0016 "Caption is missing" is thrown on API pages of type API.

In this example a global variable on the page. On a API page I personally don't set any captions, because the Name of the field property is used.

Is it possible to suppress these warning on the follow objects?
* API-object with PageType = API
* Query-object with QueryType = API

**Comment by StefanMaron** [comment]
Thanks for pointing this out. 
Of course caption should not be mandatory on API pages.

**Comment by dsaveyn** [comment]
Any update on this?
