### ISSUE TITLE
Nolint for selected procedures

### ISSUE THREAD

**Issue by jiwanovski87** [StefanMaron/BusinessCentral.LinterCop#193]
Hi,

in different other programming languages / linters we do have the possibilty to mark a function / procedure or single lines of to to not lint or even just not check a special linting rule.

Is there anything possible with LinterCop?

As example from Golang / Golangci-lint
https://golangci-lint.run/usage/false-positives/
![image](https://user-images.githubusercontent.com/14943914/162442180-f5c7d51c-eb5b-4532-bb79-83733924ac7a.png)

**Comment by jiwanovski87** [comment]
In addition: I am interested in this to mark some procedures to not get the LC0010....
We do have a big solution and I want to ensure that nobody will create a complex procedure anymore. But there are some existing which I would like to exclude...

**Comment by StefanMaron** [comment]
Yes, that works with pragmas.
Read here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/directives/devenv-directive-pragma-warning

![image](https://user-images.githubusercontent.com/24838311/162442434-7ab4cded-ae84-4325-b7f7-aa7d97589ecf.png)
![image](https://user-images.githubusercontent.com/24838311/162442478-34c0ceb1-6c78-4430-af57-83850f7030df.png)

**Comment by StefanMaron** [comment]
You should also see a quick fix to surround a like with that pragma if you have the AL Toolbox installed:
![image](https://user-images.githubusercontent.com/24838311/162442836-d42be27e-e38e-4b3d-a4d6-e30c0dd3ad82.png)
![image](https://user-images.githubusercontent.com/24838311/162442878-95a10aa5-bbdb-435f-bbef-5ad44a21f899.png)
