### ISSUE TITLE
[LC0016] Caption is Missing when TableExt is used

### ISSUE THREAD

**Issue by Axarath** [StefanMaron/BusinessCentral.LinterCop#196]
I have several cases when captions are missing in table in Base Application. Tried to fix it by TableExt but this is ignored on pages.
It still shows "Caption is missing".

**Comment by StefanMaron** [comment]
Do you have an example for me? Then it will be easier to reproduce :)

**Comment by Axarath** [comment]
Tested in BC 18.6
Example: 

- table 7001 table 7001 "Price List Line" - missing Caption in "Currency Code" field
- new tableext when this missing Caption is fixed (created)
- created new page with sourcetable = "Price List Line" - field "Currency Code" detected as "Caption is missing"

**Comment by StefanMaron** [comment]
I have tested this and it seems like this is currently not possible to pick up.

**Comment by StefanMaron** [comment]
I checked again if I can get the to TableExtension definition and read the caption, but I did not find a way to achieve this. 
I think MS added the caption for this particular field, so I will close this issue now as `not possible`
