### ISSUE TITLE
Unable to load Analyzer

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#200]
I am getting this error

Unable to load Analyzer assembly c:\Users\userName\.vscode\extensions\ms-dynamics-smb.al-9.3.646020\bin\Analyzers\BusinessCentral.LinterCop.dll : File c:\Users\userName\.vscode\extensions\ms-dynamics-smb.al-9.3.646020\bin\Analyzers\BusinessCentral.LinterCop.dll was not found.

I have uninstalled/reinstalled the extension a number of times.  I cannot find the DLL in the .vscode\extensions folder anywhere.

What am I missing?

Full content of "problem"

```
[{
	"resource": "/c:/Users/userName/Documents/AL/AdvancedSampleExtension/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "AL1005",
		"target": {
			"$mid": 1,
			"external": "https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al1005",
			"path": "/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al1005",
			"scheme": "https",
			"authority": "docs.microsoft.com"
		}
	},
	"severity": 4,
	"message": "Unable to load Analyzer assembly c:\\Users\\userName\\.vscode\\extensions\\ms-dynamics-smb.al-9.3.646020\\bin\\Analyzers\\BusinessCentral.LinterCop.dll : File c:\\Users\\userName\\.vscode\\extensions\\ms-dynamics-smb.al-9.3.646020\\bin\\Analyzers\\BusinessCentral.LinterCop.dll was not found.",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

```

**Comment by StefanMaron** [comment]
The download is done via powershell, I have seen this problem when the execution policy is setup to be too restrictive.

/Stefan
________________________________
Von: tscottjendev ***@***.***>
Gesendet: Tuesday, July 5, 2022 5:11:22 PM
An: StefanMaron/BusinessCentral.LinterCop ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [StefanMaron/BusinessCentral.LinterCop] Unable to load Analyzer (Issue #200)


I am getting this error

Full content of "problem"

Unable to load Analyzer assembly c:\Users<userName>.vscode\extensions\ms-dynamics-smb.al-9.3.646020\bin\Analyzers\BusinessCentral.LinterCop.dll : File c:\Users<userName>.vscode\extensions\ms-dynamics-smb.al-9.3.646020\bin\Analyzers\BusinessCentral.LinterCop.dll was not found.

I have uninstalled/reinstalled the extension a number of times. I cannot find the DLL in the .vscode\extensions folder anywhere.

What am I missing?

[{
        "resource": "/c:/Users/tscott/Documents/AL/AdvancedSampleExtension/app.json",
        "owner": "_generated_diagnostic_collection_name_#0",
        "code": {
                "value": "AL1005",
                "target": {
                        "$mid": 1,
                        "external": "https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al1005",
                        "path": "/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al1005",
                        "scheme": "https",
                        "authority": "docs.microsoft.com"
                }
        },
        "severity": 4,
        "message": "Unable to load Analyzer assembly c:\\Users\\tscott\\.vscode\\extensions\\ms-dynamics-smb.al-9.3.646020\\bin\\Analyzers\\BusinessCentral.LinterCop.dll : File c:\\Users\\tscott\\.vscode\\extensions\\ms-dynamics-smb.al-9.3.646020\\bin\\Analyzers\\BusinessCentral.LinterCop.dll was not found.",
        "source": "AL",
        "startLineNumber": 1,
        "startColumn": 1,
        "endLineNumber": 1,
        "endColumn": 1
}]

**Comment by tscottjendev** [comment]
That may be so in my case.  I did run VSC as administrator and ran the "Install from VSIX" after downloading it.  Still the same issue.  Where does PowerShell come in?  Can I run it manually somehow?

**Comment by tscottjendev** [comment]
This is my current Execution-Policy state:
![image](https://user-images.githubusercontent.com/102963427/177540398-1ff792ba-7ce0-4a08-a612-933a5db3e724.png)
So I am not sure what the problem is but I will try the new release and see what happens.  Thank you for the effort.

**Comment by StefanMaron** [comment]
If it is set to unrestricted, I dont think my "fix" will change anything 

Could you have a look at the console insight the developer tools from VS Code while trying to download?
![image](https://user-images.githubusercontent.com/24838311/177541110-11435155-0e9f-4e77-a4b1-f012fcc44211.png)

Maybe clear the console until you do not see any entries coming in:
![image](https://user-images.githubusercontent.com/24838311/177541224-ece7071e-018d-446a-b814-a56de90fae97.png)

Then trigger the download manually:
![image](https://user-images.githubusercontent.com/24838311/177541300-eb8f1ffc-55fb-4b4c-bdc9-ff8763645217.png)

Maybe we can see from the console whats going on

**Comment by tscottjendev** [comment]
I don't see anything that shows anything special.  See attached video

https://user-images.githubusercontent.com/102963427/177550932-575beff8-9cfc-46ec-b57a-d98e82963140.mp4

**Comment by StefanMaron** [comment]
Please also run that action to trigger the download. 
Did you turn off autodownload in some of the settings by any chance?

`"linterCop.autoDownload": true,`

**Comment by tscottjendev** [comment]
I added that.  Still no luck.
https://user-images.githubusercontent.com/102963427/177705326-c7f41988-4cc0-4bae-9076-7a2a66aea20a.mp4

Here are the settings from my workspace file.
```
	"settings": {
		"al.codeAnalyzers": [
			"${CodeCop}",
			"${UICop}",
			"${PerTenantExtensionCop}",
			"${AppSourceCop}",
			"${analyzerFolder}BusinessCentral.LinterCop.dll"
		],
		"al.enableCodeAnalysis": true,
		"al.backgroundCodeAnalysis": true,
		"al.ruleSetPath": "ruleset.json",
		"CRS.FileNamePattern": "<ObjectNameShort>.<ObjectType>.al",
		"CRS.ObjectNamePrefix": "ASE ",
		"CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
		"linterCop.autoDownload": true
	}

```

**Comment by tscottjendev** [comment]
Just remembered one thing.  We have a proxy firewall and that has caused some issues in the past.  I am working at a government regulated utility and have little control over that infrastructure.  Is there maybe VS Code setting I need to add/update to handle the proxy?

**Comment by StefanMaron** [comment]
I have no idea.

But you also do not need the vs code extension to auto download. 
You can download the dll manually from the releases here https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.25.5

and then place it either in the folder you already posted here, or place it some where and use the full path in the code analyzer setting.

Make sure to verify in properties of the dll that it is allowed to execute. Downloaded dlls sometimes have a lock on them for security reasons
