### ISSUE TITLE
LinterCop.json Spelling issues

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#216]
There are a couple of spelling mistakes in the entries for the LinterCop.json
```
{
    "cyclomaticComplexetyThreshold": 6,
    "maintainablityIndexThreshold": 55,
    "enableRule0011ForTableFields": true
}
```
cyclomaticComplexetyThreshold should be cyclomaticComplex**i**tyThreshold
and 
maintainablityIndexThreshold should be maintainab**i**lityIndexThreshold

Can you change these without breaking changes? Can you introduce a schema for the file like there is for app.json or launch.json?  In the schema can you deprecate entries?

**Comment by StefanMaron** [comment]
I do not know how to provide a schema for this file. Would need to check.

I probably need to support both, the current spelling and the correct one, for a period of time to not break everyone
