### ISSUE TITLE
[LC0006] Wrong Error message about AutoIncrement  since version v0.25.9

### ISSUE THREAD

**Issue by ChrisKappe** [StefanMaron/BusinessCentral.LinterCop#220]
Hi

I got the new version v0.25.9 deployed this morning. Since then I get a strange error message tagged with LC0006.

`       field(16; "OGDT Merge Invoices"; Option)
        {
            Caption = 'Merge Invoices', Comment = 'nl-NL=Verkoopfacturen samenvoegen';
            DataClassification = CustomerContent;
            OptionCaptionML = ENU = ' ,Reference,Shipment Date,External Doc. No.',
                              NLD = ' ,Referentie,Verzenddatum,Extern documentnr.';
            OptionMembers = " ",Reference,"Shipment Date","External Doc. No.";
        }`

The "OptionMembers" line gets marked with "error LC0006: AutoIncrement fields are not possible in temporary tables!"

// Christian

**Comment by StefanMaron** [comment]
Oh thats interesting, thanks for reporting!

Its strange that I dont get this error.

What version of the AL Extension are you using?

**Comment by ChrisKappe** [comment]
Hi Stefan,

I'm running right now v10.0.687650

**Comment by StefanMaron** [comment]
hm so thats not the problem. But as I said, If I paste the code you provided into a table I dont get a warning.

Could you provide me a small sample app to reproduce? Then I can see what the problem is

**Comment by ChrisKappe** [comment]
Hi Stefan,
strange... just ran al go to create the sample project for you.
Now after switching between the projects, the issue seems gone.
I closed and reopened VS Code before, that did not do the trick.
Will see if I get it again - but for now we can close this issue.
