### ISSUE TITLE
LC0016 false positive on SplitButton groups

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#223]
LC0016 complains if a caption is missing on the new promoted action groups where you have `ShowAs = SplitButton`.
When using SplitButton, you should not add a caption to the group since the caption from first actionref is used instead.

![image](https://user-images.githubusercontent.com/23032645/195075135-01ee1406-993a-405e-b38d-d86a69dfc366.png)

**Comment by StefanMaron** [comment]
Thanks for reporting, I looked at this right away, please check if it works now

**Comment by jwikman** [comment]
Blitzing fast!

Seems to work just as wanted. 👍

Thanks Stefan.
