### ISSUE TITLE
Suggestion: Remove fieldgroup is missing for Setup Tables

### ISSUE THREAD

**Issue by ShareTEC** [StefanMaron/BusinessCentral.LinterCop#241]
With the latest update there is a "Fieldgroup brick/dropdown is missing on table" info. I think that's a good addition. But for setup tables this "requirement" should be removed (I think), as it doesn't make sense.
It would be easy to check if you could define a "type" for your table. Now you can only do this based on the name of a table. Maybe you have other suggestions?

**Comment by StefanMaron** [comment]
That makes sense, but I think I can just tie it the „Primary Key“ field

/Stefan
________________________________
Von: Kevin Smet ***@***.***>
Gesendet: Monday, November 14, 2022 10:43:29 AM
An: StefanMaron/BusinessCentral.LinterCop ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [StefanMaron/BusinessCentral.LinterCop] Suggestion: Remove fieldgroup is missing for Setup Tables (Issue #241)


With the latest update there is a "Fieldgroup brick/dropdown is missing on table" info. I think that's a good addition. But for setup tables this "requirement" should be removed (I think), as it doesn't make sense.
It would be easy to check if you could define a "type" for your table. Now you can only do this based on the name of a table. Maybe you have other suggestions?

**Comment by ShareTEC** [comment]
Yep.. that would work.

**Comment by Arthurvdv** [comment]
Hi @ShareTEC, I've created an PR for this. Could you review this PR whether it meets your expectations?
