### ISSUE TITLE
LC0005 field datatype with length 

### ISSUE THREAD

**Issue by Jupentti1** [StefanMaron/BusinessCentral.LinterCop#248]
Incorrectly cased field data types with length e.g. text[10] will not give LC0005 warning.

        field(2; Subject; text[10])
        {
            DataClassification = CustomerContent;
        }
        field(3; Body; coDe[10])
        {
            DataClassification = CustomerContent;
        }

**Comment by Arthurvdv** [comment]
This should now be resolved in the release version of [v0.30.25](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.25) of the LinterCop.
