### ISSUE TITLE
Please add setting to disable update notice.

### ISSUE THREAD

**Issue by mjmatthiesen** [StefanMaron/BusinessCentral.LinterCop#257]
I get these constantly. They seem to be bugged because every vs code reload shows it. I would just prefer to disable this than see them at all.

![image](https://user-images.githubusercontent.com/16603906/208517772-4b07154e-4459-493f-9fa6-e0fc226dc742.png)

**Comment by pri-kise** [comment]
Have you tried the setting icon on the right upper corner?
Normaly these enable to disable notifications of an extension

**Comment by mjmatthiesen** [comment]
There's no choices to disable them, no.

**Comment by Arthurvdv** [comment]
I don't believe I've ever seen this popup in VS Code.

This seems a VS Code extension issue not so much an issue of the LinterCop as a CodeCop itself. If this still is a persistent issue, please open an new issue here: https://github.com/StefanMaron/vsc-lintercop/issues.
