### ISSUE TITLE
Rule0015PermissionSetCoverage runtime error

### ISSUE THREAD

**Issue by f4n0** [StefanMaron/BusinessCentral.LinterCop#277]
Hi, I've got this error, and I don't know why!:

[{
	"resource": "",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'BusinessCentral.LinterCop.Design.Rule0015PermissionSetCoverage' threw an exception of type 'System.MissingFieldException' with message 'System.MissingFieldException: Field not found: 'Microsoft.Dynamics.Nav.Analyzers.Common.Constants.PermissionNodeXPath'.\r\n   at BusinessCentral.LinterCop.Design.Rule0015PermissionSetCoverage.XmlPermissionExistsForObject(IEnumerable`1 permissionSetDocuments, PermissionObjectKind objectType, Int32 objectId)\r\n   at BusinessCentral.LinterCop.Design.Rule0015PermissionSetCoverage.CheckPermissionSetCoverage(SymbolAnalysisContext context)\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 658\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1102'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by StefanMaron** [comment]
which version of the AL Language extension are you using?
Is it possible to reproduce this in a minimal al project?

**Comment by Arthurvdv** [comment]
@f4n0, we need more details to try to reproduce this error. Do you have the requested information that @StefanMaron had mentioned here?

**Comment by f4n0** [comment]
sorry for ghosting this issue!
unfortunately, I wasn't able to reproduce this issue in any way! 
I suppose there is something strange in my code!

If I'm the only one with this, you could close this issue until further notice!

**Comment by Arthurvdv** [comment]
Thank you for sharing the update and good to know the issue seems to be resolved.
