### ISSUE TITLE
Rule189

### ISSUE THREAD

**Issue by tausav** [StefanMaron/BusinessCentral.LinterCop#279]
I'm getting error:
[{
	"resource": "/c:/AL Projects/S4LEASING-AUS/MainApp/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'Microsoft.Dynamics.Nav.CodeCop.Design.Rule189ApplicationAreaHasInvalidValue' threw an exception of type 'System.ArgumentException' with message 'System.ArgumentException: An item with the same key has already been added. Key: S4LALeasing\r\n   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule189ApplicationAreaHasInvalidValue.ExtractAppAreaFromFields(PooledList`1 fields, PooledNameObjectDictionary`1 appAreas, StringBuilder stringBuilder) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule189ApplicationAreaHasInvalidValue.cs:line 155\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule189ApplicationAreaHasInvalidValue.GetApplicationAreas(CompilationStartAnalysisContext ctx, String& validAppAreasOrder) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule189ApplicationAreaHasInvalidValue.cs:line 131\r\n   at Microsoft.Dynamics.Nav.CodeCop.Design.Rule189ApplicationAreaHasInvalidValue.<Initialize>b__3_0(CompilationStartAnalysisContext compilationStartAnalysisContext) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeCop\\Design\\Rule189ApplicationAreaHasInvalidValue.cs:line 34\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1102'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by Arthurvdv** [comment]
hi @tausav, can you provide a small code example for us to reproduce this error? I'm not sure if this is related to the BusinessCentral.LinterCop, but I could have a look and see if I can help.

**Comment by Arthurvdv** [comment]
@tausav, are you still experiencing this problem?

**Comment by tausav** [comment]
@Arthurvdv Sorry that didn't response. I find out a reason of this issue. It is because of one app where are added 2 fields with almost identical names (one is with space and another without) on "Application Area Setup" table extension. One of those fields is marked as obsolete
