### ISSUE TITLE
Warning in RuleSet for LC rules

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#300]
I am seeing warnings when I view/edit my ruleset.json files for LC0009 and LC0010 (only ones of BCLinterCop I specify).  The warning says, basically only MS codes accepted.  Is this something you can fix or does MS have to do something?

BCLinterCop version: v0.1.5
AL Language version: v11.0.810452
VS Code info: 
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

> Value is not accepted. Valid values: "AS0110", "AS0111", "AS0112", "AS0113", "AS0050", "AS0066", "AS0105", "AS0082", "AS0083", "AS0064", "AS0065", "AS0067", "AS0029", "AS0030", "AS0031", "AS0032", "AS0033", "AS0088", "AS0089", "AS0090", "AS0002", "AS0004", "AS0005", "AS0036", "AS0041", "AS0044", "AS0080", "AS0086", "AS0069", "AS0070", "AS0071", "AS0009", "AS0010", "AS0038", "AS0042", "AS0043", "AS0001", "AS0006", "AS0034", "AS0039", "AS0068", "AS0109", "AS0011", "AS0098", "AS0099", "AS0072", "AS0073", "AS0074", "AS0075", "AS0076", "AS0003", "AS0091", "AS0096", "AS0097", "AS0018", "AS0019", "AS0020", "AS0021", "AS0022", "AS0023", "AS0024", "AS0025", "AS0026", "AS0027", "AS0028", "AS0049", "AS0063", "AS0077", "AS0078", "AS0101", "AS0102", "AS0106", "AS0107", "AS0108", "AS0114", "AS0095", "AS0059", "AS0061", "AS0011", "AS0054", "AS0079", "AS0098", "AS0013", "AS0099", "AS0058", "AS0060", "AS0062", "AS0094", "AS0103", "AS0014", "AS0015", "AS0047", "AS0048", "AS0051", "AS0052", "AS0053", "AS0081", "AS0084", "AS0085", "AS0092", "AS0100", "AS0104", "AS0016", "AS0055", "AS0056", "AS0057", "AS0087", "AA0001", "AA0002", "AA0003", "AA0005", "AA0008", "AA0013", "AA0018", "AA0021", "AA0022", "AA0040", "AA0074", "AA0215", "AA0241", "AA0073", "AA0237", "AA0072", "AA0216", "AA0217", "AA0218", "AA0219", "AA0220", "AA0221", "AA0223", "AA0224", "AA0225", "AA0226", "AA0448", "AA0462", "AA0470", "AA0240", "AA0050", "AA0051", "AA0052", "AA0053", "AA0181", "AA0233", "AA0235", "AA0242", "AA0087", "AA0100", "AA0101", "AA0102", "AA0103", "AA0104", "AA0105", "AA0106", "AA0131", "AA0136", "AA0137", "AA0139", "AA0150", "AA0161", "AA0175", "AA0189", "AA0199", "AA0200", "AA0201", "AA0194", "AA0198", "AA0202", "AA0203", "AA0204", "AA0244", "AA0245", "AA0207", "AA0210", "AA0211", "AA0213", "AA0222", "AA0227", "AA0228", "AA0230", "AA0231", "AA0243", "AA0246", "AA0232", "AA0205", "AA0206", "AA0214", "PTE0006", "PTE0007", "PTE0003", "PTE0004", "PTE0001", "PTE0002", "PTE0013", "PTE0014", "PTE0016", "PTE0017", "PTE0018", "PTE0019", "PTE0008", "PTE0005", "PTE0009", "PTE0010", "PTE0011", "PTE0012", "PTE0015", "PTE0020", "AW0001", "AW0002", "AW0003", "AW0004", "AW0005", "AW0006", "AW0007", "AW0008", "AW0009", "AW0010", "AW0011", "AW0012", "AW0013", "AW0014", "AW0015", "AL0000", "AL0100", "AL0101", "AL0102", "AL0103", "AL0104", "AL0105", "AL0106", "AL0107", "AL0108", "AL0109", "AL0110", "AL0111", "AL0112", "AL0113", "AL0114", "AL0115", "AL0116", "AL0117", "AL0118", "AL0119", "AL0120", "AL0121", "AL0122", "AL0123", "AL0124", "AL0125", "AL0126", "AL0127", "AL0128", "AL0129", "AL0130", "AL0131", "AL0132", "AL0133", "AL0134", "AL0135", "AL0136", "AL0137", "AL0138", "AL0139", "AL0140", "AL0142", "AL0143", "AL0144", "AL0145", "AL0146", "AL0147", "AL0148", "AL0149", "AL0150", "AL0151", "AL0152", "AL0153", "AL0154", "AL0155", "AL0156", "AL0157", "AL0158", "AL0159", "AL0160", "AL0161", "AL0162", "AL0163", "AL0164", "AL0165", "AL0166", "AL0167", "AL0168", "AL0169", "AL0170", "AL0171", "AL0172", "AL0173", "AL0174", "AL0175", "AL0176", "AL0177", "AL0178", "AL0179", "AL0180", "AL0181", "AL0182", "AL0183", "AL0184", "AL0185", "AL0186", "AL0187", "AL0189", "AL0190", "AL0191", "AL0192", "AL0193", "AL0195", "AL0196", "AL0197", "AL0198", "AL0199", "AL0200", "AL0201", "AL0202", "AL0203", "AL0204", "AL0206", "AL0207", "AL0208", "AL0210", "AL0211", "AL0212", "AL0213", "AL0214", "AL0215", "AL0216", "AL0217", "AL0218", "AL0219", "AL0220", "AL0221", "AL0222", "AL0223", "AL0224", "AL0227", "AL0228", "AL0229", "AL0230", "AL0231", "AL0232", "AL0234", "AL0235", "AL0236", "AL0238", "AL0239", "AL0240", "AL0241", "AL0242", "AL0243", "AL0244", "AL0245", "AL0246", "AL0247", "AL0249", "AL0250", "AL0251", "AL0252", "AL0254", "AL0255", "AL0256", "AL0257", "AL0259", "AL0260", "AL0261", "AL0262", "AL0263", "AL0264", "AL0266", "AL0267", "AL0268", "AL0269", "AL0270", "AL0271", "AL0272", "AL0273", "AL0274", "AL0275", "AL0276", "AL0277", "AL0278", "AL0279", "AL0280", "AL0281", "AL0282", "AL0283", "AL0284", "AL0285", "AL0286", "AL0287", "AL0288", "AL0290", "AL0291", "AL0292", "AL0293", "AL0294", "AL0295", "AL0296", "AL0297", "AL0298", "AL0299", "AL0300", "AL0301", "AL0302", "AL0303", "AL0304", "AL0305", "AL0306", "AL0307", "AL0308", "AL0309", "AL0310", "AL0311", "AL0313", "AL0314", "AL0315", "AL0316", "AL0317", "AL0318", "AL0319", "AL0320", "AL0321", "AL0322", "AL0323", "AL0324", "AL0325", "AL0326", "AL0327", "AL0329", "AL0331", "AL0332", "AL0333", "AL0334", "AL0335", "AL0336", "AL0337", "AL0338", "AL0340", "AL0341", "AL0342", "AL0343", "AL0344", "AL0345", "AL0346", "AL0347", "AL0349", "AL0350", "AL0351", "AL0352", "AL0353", "AL0354", "AL0355", "AL0356", "AL0357", "AL0358", "AL0359", "AL0360", "AL0361", "AL0362", "AL0363", "AL0364", "AL0365", "AL0366", "AL0367", "AL0368", "AL0369", "AL0370", "AL0371", "AL0372", "AL0373", "AL0374", "AL0375", "AL0376", "AL0377", "AL0378", "AL0379", "AL0380", "AL0381", "AL0382", "AL0383", "AL0384", "AL0385", "AL0386", "AL0387", "AL0388", "AL0389", "AL0390", "AL0391", "AL0392", "AL0393", "AL0395", "AL0396", "AL0397", "AL0398", "AL0399", "AL0401", "AL0402", "AL0403", "AL0404", "AL0405", "AL0406", "AL0407", "AL0408", "AL0409", "AL0410", "AL0411", "AL0412", "AL0413", "AL0414", "AL0415", "AL0416", "AL0417", "AL0418", "AL0419", "AL0420", "AL0421", "AL0422", "AL0423", "AL0424", "AL0425", "AL0426", "AL0427", "AL0428", "AL0429", "AL0430", "AL0432", "AL0433", "AL0434", "AL0435", "AL0436", "AL0437", "AL0438", "AL0439", "AL0440", "AL0441", "AL0442", "AL0443", "AL0444", "AL0445", "AL0447", "AL0448", "AL0449", "AL0450", "AL0451", "AL0452", "AL0453", "AL0454", "AL0455", "AL0456", "AL0457", "AL0458", "AL0459", "AL0460", "AL0461", "AL0462", "AL0463", "AL0464", "AL0465", "AL0466", "AL0467", "AL0468", "AL0470", "AL0471", "AL0472", "AL0473", "AL0474", "AL0475", "AL0476", "AL0477", "AL0478", "AL0479", "AL0480", "AL0481", "AL0482", "AL0483", "AL0484", "AL0485", "AL0486", "AL0487", "AL0488", "AL0489", "AL0490", "AL0491", "AL0492", "AL0493", "AL0494", "AL0495", "AL0496", "AL0498", "AL0499", "AL0500", "AL0501", "AL0502", "AL0503", "AL0504", "AL0505", "AL0509", "AL0510", "AL0511", "AL0512", "AL0513", "AL0514", "AL0515", "AL0516", "AL0517", "AL0518", "AL0519", "AL0520", "AL0521", "AL0522", "AL0523", "AL0524", "AL0525", "AL0526", "AL0527", "AL0528", "AL0529", "AL0530", "AL0531", "AL0532", "AL0533", "AL0534", "AL0535", "AL0536", "AL0537", "AL0538", "AL0539", "AL0540", "AL0541", "AL0542", "AL0543", "AL0544", "AL0545", "AL0546", "AL0547", "AL0548", "AL0549", "AL0550", "AL0551", "AL0552", "AL0553", "AL0554", "AL0555", "AL0556", "AL0557", "AL0558", "AL0559", "AL0560", "AL0561", "AL0562", "AL0563", "AL0564", "AL0565", "AL0566", "AL0567", "AL0568", "AL0569", "AL0570", "AL0571", "AL0572", "AL0573", "AL0574", "AL0575", "AL0576", "AL0577", "AL0578", "AL0579", "AL0580", "AL0581", "AL0582", "AL0584", "AL0585", "AL0586", "AL0587", "AL0588", "AL0589", "AL0590", "AL0591", "AL0592", "AL0593", "AL0594", "AL0595", "AL0596", "AL0598", "AL0599", "AL0600", "AL0601", "AL0602", "AL0603", "AL0604", "AL0605", "AL0606", "AL0607", "AL0608", "AL0609", "AL0610", "AL0611", "AL0612", "AL0613", "AL0614", "AL0615", "AL0616", "AL0617", "AL0619", "AL0620", "AL0621", "AL0622", "AL0623", "AL0624", "AL0625", "AL0626", "AL0627", "AL0628", "AL0629", "AL0630", "AL0631", "AL0632", "AL0633", "AL0634", "AL0635", "AL0636", "AL0637", "AL0638", "AL0639", "AL0640", "AL0641", "AL0642", "AL0643", "AL0644", "AL0645", "AL0646", "AL0647", "AL0648", "AL0649", "AL0650", "AL0651", "AL0652", "AL0653", "AL0654", "AL0655", "AL0656", "AL0657", "AL0658", "AL0659", "AL0660", "AL0665", "AL0666", "AL0667", "AL0668", "AL0670", "AL0671", "AL0672", "AL0673", "AL0674", "AL0675", "AL0676", "AL0677", "AL0679", "AL0680", "AL0681", "AL0682", "AL0683", "AL0684", "AL0685", "AL0686", "AL0687", "AL0688", "AL0689", "AL0690", "AL0691", "AL0692", "AL0693", "AL0694", "AL0695", "AL0696", "AL0697", "AL0698", "AL0700", "AL0702", "AL0704", "AL0705", "AL0706", "AL0707", "AL0708", "AL0709", "AL0710", "AL0711", "AL0712", "AL0713", "AL0714", "AL0715", "AL0716", "AL0717", "AL0718", "AL0719", "AL0720", "AL0721", "AL0722", "AL0723", "AL0724", "AL0725", "AL0726", "AL0727", "AL0728", "AL0729", "AL0730", "AL0731", "AL0732", "AL0733", "AL0734", "AL0735", "AL0736", "AL0737", "AL0738", "AL0739", "AL0740", "AL0741", "AL0742", "AL0743", "AL0744", "AL0745", "AL0746", "AL0748", "AL0749", "AL0750", "AL0751", "AL0752", "AL0753", "AL0754", "AL0755", "AL0756", "AL0757", "AL0758", "AL0759", "AL0760", "AL0761", "AL0762", "AL0763", "AL0764", "AL0765", "AL0766", "AL0767", "AL0768", "AL0769", "AL0772", "AL0999", "AL1000", "AL1001", "AL1002", "AL1003", "AL1004", "AL1005", "AL1006", "AL1007", "AL1008", "AL1009", "AL1010", "AL1011", "AL1012", "AL1013", "AL1014", "AL1015", "AL1017", "AL1018", "AL1019", "AL1021", "AL1022", "AL1023", "AL1024", "AL1025", "AL1026", "AL1028", "AL1029", "AL1030", "AL1031", "AL1032", "AL1033", "AL1034", "AL1035", "AL1036", "AL1037", "AL1038", "AL1039", "AL1040", "AL1041", "AL1042", "AL1043", "AL1044", "AL1045", "AL1046", "AL1047", "AL1048", "AL1049", "AL1050", "AL1051", "AL1052", "AL1053", "AL1054", "AL1055", "AL1056", "AL1057", "AL1058", "AL1059", "AL1060", "AL1061", "AL1062", "AL1063", "AL1064", "AL1065", "AL1066", "AL1067", "AL1068", "AL1069", "AL1070", "AL1071", "AL1072", "AL1073", "AL1074", "AL1075", "AL1076", "AL1077", "AL1078", "AL1079", "AL1080", "AL1100", "AL1101", "AL1130", "AL1150", "AL1151", "AL1152", "AL1401", "AL1402", "AL1403", "AL1404", "AL1405", "AL1406", "AL1407", "AL1408", "AL1409", "AL1410", "AL1411", "AL1412", "AL1413", "AL1414", "AL1415", "AL1416", "AL1417", "AL1418", "AL1419", "AL1420", "AL1421", "AL1422", "AL-0002", "AL-0001".

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/102963427/47147397-02de-46a4-8cca-c2dc1dee8e06)

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/102963427/d60a6a4b-90a9-4cb4-b0f9-ce40db0f2261)

**Comment by Arthurvdv** [comment]
Strange, I would expect that the rules of the LinterCop would be there.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/8b6a7522-1605-42a1-9c34-0a576acead72)

Does the LinterCop work in VS Code project? Do you get any warnings/info on the AL files?

**Comment by Arthurvdv** [comment]
@tscottjendev, are you still encountering this issue?

**Comment by tscottjendev** [comment]
Seems to be fixed now.

**Comment by Arthurvdv** [comment]
Thank you for the feedback!
