### ISSUE TITLE
InherentPermissions for objects (LC0015)

### ISSUE THREAD

**Issue by ernestasjuska** [StefanMaron/BusinessCentral.LinterCop#303]
Hi,

Since BC runtime 11.0, objects have new property `InherentPermissions` that can be used to set default permissions for objects. https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-inherentpermissions-property

The analyzer should be changed to not require permission set for object if `InherentPermissions` already adds _all direct_ permissions. For example, if table has only `InherentPermissions = rimX;`, it would still require permission set with `RIMDX`.

Example from System Application:
https://github.com/microsoft/ALAppExtensions/blob/3088b2280bf471d367efe7639763aa6f10dcfe96/Modules/System/User%20Login%20Times/src/UserLogin.Table.al#L6-L10

Thanks.

**Comment by ChristianHovenbitzer** [comment]
I created a pull request for this issue.
https://github.com/StefanMaron/BusinessCentral.LinterCop/pull/312

**Comment by ernestasjuska** [comment]
Hi, it works perfectly. Thank you both @ChristianHovenbitzer @Arthurvdv.
