### ISSUE TITLE
Cancellation tokens are not used in implementations

### ISSUE THREAD

**Issue by BazookaMusic** [StefanMaron/BusinessCentral.LinterCop#304]
Looking at issues like this:
https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/284

It seems there are some rules that may be long running. I'd suggest invoking
`context.CancellationToken.ThrowIfCancellationRequested()` in reasonable checkpoints in the code .

This ensures that if the user types something while the rule is running, the compiler will not have to wait for long running rules to finish and should improve the perceived performance of all rules.

**Comment by Arthurvdv** [comment]
That seems like a good idea to do. Is that something you're willing to create a PR for? Or maybe can you share an example of an implementation of this?

**Comment by Arthurvdv** [comment]
Am I doing this right?

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/e9691875-9631-4621-b10e-83831ecfa05e)

Ive added some cancellation tokens within the foreach loops, unfortunately this decreases the performance.

Before
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/08565027-9b5c-47c5-a2bc-710697e06b28)

After
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/3c69e8cb-fcff-4893-ac68-78d7924dc800)

It could have a beneficial effect on working in VS Code, where modifying the AL code would interrupt this rule from executing the current run and start a new one.

I'm afraid to solve the performance issue on this, is to improve the code itself. This is a complex rule covering all kind of exceptions, which makes is hard to implement changes without breaking the rule.

**Comment by Arthurvdv** [comment]
With the improvements brought by @dannoe, it seems that cancellation tokens aren't needed anymore.

**Comment by Arthurvdv** [comment]
Oops, that's not right! 😳

The cancellation tokens are now implemented and with the other code improvements together, this has resolves the performance issues.

**Comment by BazookaMusic** [comment]
Oops I missed this in a sea of notifications.

Awesome work, as you mentioned before it's about VSCode perceived performance. Cancellation tokens can't increase performance but they can make the diagnostics snappier because the rule will be cancelled faster on code changes.
It made a big difference on the microsoft AL analyzers.

My suggestion is to always employ cancellation tokens on all rules and the best place to check for it is in larger bodies of work. So it's not worth checking for it on every single tree node but it's worth checking it on every symbol or application object.
