### ISSUE TITLE
AL Pre-release support?

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#307]
@StefanMaron 
I tend to use the **Pre-release** version of the AL language extension more, resulting in BCLinterCop not running any longer.
Any chance to provide support for BCLinterCop with AL Pre-release option?

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/25268332/4bf5e271-9b34-41a6-bfe2-e10af739b4af)

**Comment by jwikman** [comment]
@StefanMaron what happened with this? 
I thought you fixed that back in april, after the discussion in #146?

I've been using the pre-release version of AL Language the last month, and BCLinterCop seems not to work (anymore?) with that.

**Comment by jwikman** [comment]
> When switching to the Pre-Release version the LinterCop seems to be working? _(exception for the Maintainability index on the LC0010 rule. That one seems to be broken)_

I get 6200+ LC00XX warnings when switching to the Pre-Release version of the AL Language extension. 5500 of them was LC0010, but also a lot of others. It just seems as if the Lintercop dlls isn't built against that runtime.

**Comment by Arthurvdv** [comment]
@jwikman I've did a rebuild to the latest version of the AL Language (13.0.878831) and unfortunately the LC0010 rule is broken and needs to be resolved.
Created an separate issue for following up on that (https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/310).

**Comment by fvet** [comment]
@StefanMaron @Arthurvdv 

Seems like BCLinterCop is again conflicting with the latest pre-lease

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/25268332/e7f8bcfc-c255-454b-83d4-8f8156eff75a)

Versions installed

```
Name: AL Language extension for Microsoft Dynamics 365 Business Central
Id: ms-dynamics-smb.al
Description: Development tools for Dynamics 365 Business Central
Version: 13.0.878831
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
```

```
Name: BusinessCentral.LinterCop
Id: stefanmaron.businesscentral-lintercop
Description: Provides Linting for the AL Language (Business Central)
Version: 0.1.6
Publisher: Stefan Maron
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=StefanMaron.businesscentral-lintercop
```

**Comment by jwikman** [comment]
@Arthurvdv AL Language Extension Pre-Release v13.0.937154 was released yesterday, and that hangs completely when using LinterCop... 

Will there be built a LinterCop-dll for the latest Pre-release version automatically after some time, or do you need to start that manually?

**Comment by Arthurvdv** [comment]
You're right, there's indeed a new version of the AL Language released, where the LinterCop needs to be compiled again against this specific version.

There's an automation in place that will prepare a new build combined with a manual review to publish this. The new pre-release is there (and seems one or more rules are broken, I'll have to look into that)

**Comment by jwikman** [comment]
I got the updated BusinessCentral.LinterCop.dll (downloaded @8.22, so should got your updated files)
But I just get stuck in the loading of my project:
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/23032645/5c04c802-cb02-41f7-81e2-65fd83eeb174)

If I disable LinterCop and restart VSCode, my project is loaded within a few seconds.

So maybe there is some other rule that has failed, that gives us this behavior?

Do you have any AL project that triggers all LinterCop rules, so we can make sure that they still work on new versions?
