### ISSUE TITLE
Pre-Release version breaks LC0010 rule.

### ISSUE THREAD

**Issue by Arthurvdv** [StefanMaron/BusinessCentral.LinterCop#310]
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/7a75cb3a-2a18-4d9a-b786-2e098cac9db2)

The Maintainability index always returns zero with the Pre-Release version of the AL Language version 13.0.878831.

**Comment by nickgoddard777** [comment]
It's now broken on v12.1.887908 of the Al Language Extension which was released this morning

**Comment by Arthurvdv** [comment]
With the new version of AL Language Extension the Pre-Release seems to be working again for me. This is a strange issue, where I don't know what has changed. 

I have been looking into this issue, but can't create a repo when I build the LinterCop .dll locally on my machine, then somehow everything works. This makes debugging why this error occurs very difficult. I'm a bit lost what could be the difference between building the artifact with the github runner versus building locally. I've matched the .NET version, so there was no difference in that. 

@fvet, @jwikman Do you still have this issue today?

**Comment by Arthurvdv** [comment]
If you're still experiencing this issue, feel free to reopen this issue. Otherwise I'm assuming this issue has been resolved in the meantime.
