### ISSUE TITLE
Unable to load Analyzer assembly after automatically update in VS Code

### ISSUE THREAD

**Issue by oliver-kaplan-qsil** [StefanMaron/BusinessCentral.LinterCop#315]
After automatically update in VS Code I get the error:

Unable to load Analyzer assembly c:\Users\okaplan\.vscode\extensions\ms-dynamics-smb.al-12.1.883011\bin\Analyzers\BusinessCentral.LinterCop.dll : File c:\Users\okaplan\.vscode\extensions\ms-dynamics-smb.al-12.1.883011\bin\Analyzers\BusinessCentral.LinterCop.dll was not found.

Also the Command "LC: Download Linter Cop" doesn't work. Could you help me please?

**Comment by Arthurvdv** [comment]
I've never encountered this issue before, so I'm not sure on how to resolve this.

If I interpret the error message, this file is missing in the folder c:\Users\okaplan.vscode\extensions\ms-dynamics-smb.al-12.1.883011\bin\Analyzers, can you manual verify if this is indeed the case?

**Comment by Arthurvdv** [comment]
@oliver-kaplan-qsil?

**Comment by oliver-kaplan-qsil** [comment]
The file BusinessCentral.LinterCop.dll is not in the current directory C:\Users\okaplan\.vscode\extensions\ms-dynamics-smb.al-12.1.887908\bin\Analyzers. It seems that during the automatic update of LinterCop all files are copied except the file BusinessCentral.LinterCop.dll. If I copy it manually, everyting is fine.

**Comment by Arthurvdv** [comment]
Strange, I've never had this issue.

You could always do a `LC: Download Linter Cop` command from the command palette in VS Code after every update to restore the LinterCop.

This seems a VS Code extension issue. If this is a persistent issue, please open an new issue here: https://github.com/StefanMaron/vsc-lintercop/issues.
