### ISSUE TITLE
AL Language extension update breaks BCLinterCop

### ISSUE THREAD

**Issue by dsaveyn** [StefanMaron/BusinessCentral.LinterCop#316]
This morning a new version of the AL Language extension was released:

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/92365904/0561a1ca-c0e8-425d-b487-da5b20611a10)

This causes BCLinterCop to break in our pipelines:

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/92365904/022dfbd0-b54f-4deb-a13c-00f0b6506b53)

We are using a PS Script that was provides to us in the past to download the correct version of the BCLinterCop:
`https://raw.githubusercontent.com/StefanMaron/vsc-lintercop/master/DownloadFile.ps1`

I assume a new version must be uploaded?

**Comment by nickgoddard777** [comment]
I'm getting errors today as well but slightly different, all my procedures have a Maintainability Index of 0.
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/332366/9d80d811-f0e8-4d38-9b10-668ef54a3699)

**Comment by Arthurvdv** [comment]
On every update of the Language extension we need to recompile the LinterCop against this version and create a new release. In this window between the update of Microsoft and the new release of the LinterCop these issues occurs.

Wit the new release of the LinterCop (https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.1) this issue should be resolved now.
