### ISSUE TITLE
LC0003/LC0005 false positive in profile objects

### ISSUE THREAD

**Issue by ChristianHovenbitzer** [StefanMaron/BusinessCentral.LinterCop#328]
both rules seem to be broken in profile objects.
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/91181840/62785d5b-df31-4b65-b2d0-3dc1e42ef69e)

**Comment by Arthurvdv** [comment]
@ChristianHovenbitzer, thanks for reporting this issue. Version [v0.30.3](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.3) should resolve this.

**Comment by ChristianHovenbitzer** [comment]
@Arthurvdv that was fast. I wanted to fix this myself this evening. Thanks for the quick response 😀

**Comment by Arthurvdv** [comment]
This was a easy fix, where I couldn’t resist to quickly create a PR for this :-)
