### ISSUE TITLE
LC0024 - Disable by default

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#331]
Can you please disable the new rule [LC0024](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0024) by default? 

It shows up in way too much of our projects since the last update, and too our devs it does not make sense to fix / be alerted (it's a bit distracting).

In additional, when using the 'Subscribe to Event' (in AL Explorer) or 'Find Event' (via the Command Pallet) in the AL Language extension, MS seems to generate eventsubscriber code, which contains a **trailing semi-colon** as well. So, without proper codeActions to solve in batch AND update from MS to review their 'event' suggestions, it will only add up more (needless) effort from the developers to remove the semicolon.

**Comment by Arthurvdv** [comment]
For every new rule we created, we've weigh carefully what the default level of the rule needs to be (Error, Warning, Info or None). This rule was part of discussion here: https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/269.

There isn't "one size fits all" for everybody, so my advice is to disable this rule on your project, workspace as described here: [Can I disable certain rules?](https://github.com/StefanMaron/BusinessCentral.LinterCop#can-i-disable-certain-rules).

Know you can have a company wide ruleset, which you can refer to from all projects/workspaces, from where you can your custom action for this rule.
https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave1/smb/dynamics365-business-central/urls-includerulesets
```json
{
    "name": "Company ruleset",
    "rules": [
        {
            "id": "LC0024",
            "action": "None",
            "justification": "Allow procedure declaration to end with semicolon."
        }
    ]
}
```

**Comment by fvet** [comment]
If it has been carefully considered, then I'd close the issue (as we've already excluded the new rule using external rulesets indeed) ;) 

I was mainly trying to avoid questions from other devs / projects NOT using external rulesets yet, but better would be to update the project to use the company rulesets then instead.

Thanks for the feedback (and continuation of introducing new rules!)

**Comment by ernestasjuska** [comment]
It is bad idea to disable a good rule just because the standard templates are bad. There should be a pressure for VS Code AL extension authors to fix inconsistencies with their templates - I mean these inconsistencies existed for years now and some since the beginning of AL. Most of the templates I see are simply copy-paste from code that was converted from C/AL text format and because that code created using template is different from what you would write using code completion in VS Code.

At the moment, the LC0024 analyzer itself does not work properly: it complains about procedures in interfaces - they don't have body because syntax is different there.
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/53167314/739d698d-c72f-49b2-a6a5-5962110a6da1)
Same thing with control addins.
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/53167314/2647e8bc-49f9-4d23-ad2d-8b7d86e1d7b4)

**Comment by tinestaric** [comment]
@Arthurvdv 
I didn't know about "Find Event" though I have experienced it with "Implement Interface" quick action from MS, as it implements it with trailing semicolons.

I agree it can feel counter-productive, however, the idea behind the rule is consistency, I would agree that maybe some would want the opposite of the rule: "Everything needs to have a semicolon", but you'd then have the issue with snippets, that don't add a semicolon.

@ernestasjuska 
Actually, neither interfaces nor controladdins need a trailing semicolon. It's completely optional in these two object types as well.

**Comment by ernestasjuska** [comment]
@tinestaric Thanks for correcting me. I hate AL syntax even more now. 👍

**Comment by Arthurvdv** [comment]
> It is bad idea to disable a good rule just because the standard templates are bad. 

I think this sums it up 😅

On the details page of this rule, [LC0024](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0024), I’ve added an Find and Replace to fix these. Unfortunately I couldn’t get it to work on a multiline method like the one below;

![image](https://user-images.githubusercontent.com/53167314/283107319-739d698d-c72f-49b2-a6a5-5962110a6da1.png)

If there’s a RegEx specialist around, feel free to improve this or an other route could be to create request for an code action over here: https://github.com/anzwdev/al-code-outline
