### ISSUE TITLE
LC0027 Source table without LookupPageId

### ISSUE THREAD

**Issue by Arthurvdv** [StefanMaron/BusinessCentral.LinterCop#334]
@Arthurvdv To my knowledge, `pagemanagement.pagerun` would not work if the source table does not have a lookuppageid assigned (and the pagemanagement.getconditionalcardpageid does not return any value either). The new LC rule can't detect these scenario's, but might be good to list this case as a possible exception on the wiki page.

https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0027

_Originally posted by @fvet in https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/275#issuecomment-1808525375_

**Comment by Arthurvdv** [comment]
@rvanbekkum and @fvet, May I ask for your help on this wat is the best option here?

Adding an exception on the wiki page is of course possible, but I think it would be better to modify the rule a bit to prevent the following scenario's

* Source table without LookupPageId
* Not all variables are suited for the "Page Management" codeunit.

For example the scenario below would raise the LC0027 rule on the `Page.Run(Page::"Item Reclass. Journal", ItemJournalLine);` line. Changing this to the "Page Management" codeunit would make this open the wrong "Item Journal Lines" page.

```AL
internal procedure OpenItemReclassJournal(DocumentNo: Code[20])
var
    Setup: Record "Assembly Setup";
    ItemJournalLine: Record "Item Journal Line";
begin
    ItemJournalLine.SetRange("Journal Template Name", Setup."My Inv. Reclass Jnl Temp PTE");
    ItemJournalLine.SetRange("Journal Batch Name", Setup."Inv. Reclass Jnl Batch PTE");
    ItemJournalLine.SetRange("Document No.", DocumentNo);
    Page.Run(Page::"Item Reclass. Journal", ItemJournalLine);
end;
```

```AL
table 83 "Item Journal Line"
{
    Caption = 'Item Journal Line';
    DrillDownPageID = "Item Journal Lines";
    LookupPageID = "Item Journal Lines";
```

If I look into the "Page Management" codeunit, I see that the the tables below are a best fit for this codeunit. An other solution would be to only raise the LC0027 rule on one of the tables below. This would be a hardcoded solution unfortunately, so when the "Page Management" codeunit get updated, the rule needs be modified to adapt to these changes.

- "Gen. Journal Template"
- "Company Information"
- "Sales Header"
- "Purchase Header"
- "Service Header"
- "Service Contract Header"
- "Gen. Journal Batch"
- "Gen. Journal Line"
- "User Setup"
- "General Ledger Setup"
- "Sales Header Archive"
- "Purchase Header Archive"
- "Res. Journal Line"
- "Job Journal Line"
- "Item Analysis View"
- "Purchases & Payables Setup"
- "Approval Entry"
- "Doc. Exch. Service Setup"
- "Incoming Documents Setup"
- "Text-to-Account Mapping"
- "Cash Flow Setup"
- "Sales Invoice Header"
- "Production Order"
- "User"
- "Employee"

It would be great to have some feedback here on this!

**Comment by tscottjendev** [comment]
Related to this.  Some tables have card and list pages.  How does Page Management distinguish?  It doesn't seem to and it seems that it is really intended for "card" pages judging by variable and function names.  It only falls backup to Lookup pages (list) if it can't find a card.  It, notably, does not include any sort of "master" records like Customer, Vendor, Item, Fixed Asset in its functions.    Yes, it find the card id for these via default but there is no way to get the List page explicitly when I want it.

So I will have issues with this rule when I need to sometimes call customer card and other times customer list.

**Comment by pri-kise** [comment]
PageManagement is intened for Card Pages.
If I want to show several records I currently use the following approach:
```al
if PurchRcptHeader.Count() = 1 then
    PageManagement.PageRun(PurchRcptHeader)
else
    Page.Run(PageManagement.GetDefaultLookupPageIDByVar(PurchRcptHeader), PurchRcptHeader);
```

Additionally I get the warning for a Wizard on a temporary Record:

```al
local procedure OpenMyFeatureAssistedSetup(var PTESetup: Record "PTE Setup")
var
    TempPTESetup: Record "PTE Setup" temporary;
begin
    TempPTESetup.Init();
    TempPTESetup.TransferFields(PTESetup);
    TempPTESetup.Insert(false);
    Page.Run(Page::"PTE MyFeature Wizard", TempPTESetup); //Here shouldn't be a warning
    CurrPage.Update();
end;
```

**Comment by tscottjendev** [comment]
FYI, this rule does not seem to pickup `Page.RunModal()` instances at all.

**Comment by Arthurvdv** [comment]
> Additionally I get the warning for a Wizard on a temporary Record:

You're right! I'll create an extra check to exclude this rule to on temporary records.

> FYI, this rule does not seem to pickup `Page.RunModal()` instances at all. Wouldn't the same rationale apply?

It seems that I have no way to distinct if the return value from a RunModal is used or not. In the Windows Client the RunModal would prevent the user from switching to the other windows of NAV. In the WebClient this isn't the same behavior anymore. So does it make sense to use RunModal when you're not catching the return action? In that case this rule can merely focus on the Page.Run and we could create a separate rule for RunModal when no return action is defined. 

> If I look into the "Page Management" codeunit, I see that the the tables below are a best fit for this codeunit.

Quoting myself here. I'm strongly considering to bind this rule to the supported tables. Could the be reasons to keep the rule firing on all records?


So far I've tested with these possible combinations. Are there scenario's missing?

```AL
codeunit 50100 "MyCodeunit"
{
    local procedure OpenPage()
    var
        SalesHeaderRec: Record "Sales Header";
        TempSalesHeaderRec: Record "Sales Header" temporary;
        PageManagement: Codeunit "Page Management";
        SalesOrderPage: Page "Sales Order";
    begin
        // Do nothing (no Record present)
        Page.Run(Page::"Sales Order");

        // Raise the LC0027 rule
        Page.Run(Page::"Sales Order", SalesHeaderRec);

        // Raise the LC0027 rule 
        Page.Run(Page::"Sales Order", SalesHeaderRec, SalesHeaderRec.FieldNo("No."));

        // Do not Raise the LC0027 rule
        Page.Run(Page::"Sales Order", TempSalesHeaderRec);

        // Do nothing (Page has been specific declared as a variable)
        SalesOrderPage.Run();

        // Do not raise the LC0027 rule (no support for action return)
        if Page.RunModal(Page::"Sales Order List", SalesHeaderRec) = Action::LookupOK then;

        // Should raise the LC0027 rule, but at this moment no option to distinct this and the line above with use of the return value
        Page.RunModal(Page::"Sales Order List", SalesHeaderRec);

        // Do not raise the LC0027 rule when the PageID come from a Record
        Page.Run(SalesHeaderRec."Dimension Set ID", SalesHeaderRec);

        // Do not raise the LC0027 rule when entering a zero as PageID
        Page.Run(0, SalesHeaderRec);

        // Do not raise the LC0027 rule when retrieving the page by a method
        Page.Run(PageManagement.GetDefaultLookupPageIDByVar(SalesHeaderRec), SalesHeaderRec);

        // Raise the LC0027 rule when record is returned from method
        Page.Run(Page::"Sales Order", GetRecord());

        // Do not raise the LC0027 rule when a temporary record is returned from method
        Page.Run(Page::"Sales Order", GetTempRecord());

        // Handled by the LC0012 rule
        Page.Run(22, SalesHeaderRec);
    end;

    local procedure GetRecord() SalesHeader: Record "Sales Header";
    begin
    end;

    local procedure GetTempRecord() SalesHeader: Record "Sales Header" temporary;
    begin
    end;
}

page 50100 "MyPage"
{
    local procedure DoPageBackgroundTask()
    var
        TaskIdCalculateCue: Integer;
    begin
        // Do not raise a LC0027 rule on running a page for PBT
        CurrPage.EnqueueBackgroundTask(TaskIdCalculateCue, Codeunit::"AAD Application Interface");
    end;
}
```

**Comment by Arthurvdv** [comment]
Small modification on the example above. When passing a zero as PageID, we also would like to raise this rule.

```AL
// Raise the LC0027 rule
Page.Run(0, SalesHeaderRec);
```
