### ISSUE TITLE
NullReference Error - BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#350]
New error this morning.  Did not appear on Friday. 
[{
	"resource": "/c:/Repos/Jendev/JI-InternalSystem-NEW/Legacy/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.IsSingleInstanceCodeunitWithGlobalVars(ICodeunitTypeSymbol codeunitTypeSymbol)\r\n   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.ClearCodeunit(OperationAnalysisContext ctx)\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 766\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1102'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by pri-kise** [comment]
I have the same error 

```
Analyzer 'BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.IsSingleInstanceCodeunitWithGlobalVars(ICodeunitTypeSymbol codeunitTypeSymbol)
   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.ClearCodeunit(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 766
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'
```

**Comment by Arthurvdv** [comment]
Thank you for reporting this, I'll look into this.

This is probably caused the new [LC0032](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0032) that I've added to the prelease of the LinterCop.

**Comment by Arthurvdv** [comment]
I've added an extra NullReference check, where I'm hoping that this will resolve the issue.

The prerelease version has now been updated. To be sure you're using this version manually delete de LinterCop dll's in `%userprofile%\.vscode\extensions\ms-dynamics-smb.al-<version>\bin\Analyzers` and download them again with the 'LC: Download Linter Cop' command n VS Code.

Would be great if it would be possible to have a small sample AL file (or project) which causes this error (not an easy request, I know 🙈). I couldn't reproduce this error and would like to get to the bottom of this to figure out what could cause this error to occur.

**Comment by tscottjendev** [comment]
Still getting the error.  I did have a single instance Codeunit that was being cleared.  I removed that, reloaded and still got error message.  I deleted the Codeunit (old code not needed anymore).  Found another single instance Codeunit that is not used anywhere and commented out the `SingleInstance = true;`, reloaded and still get the error message.

[{
	"resource": "/c:/Repos/Jendev/JI-InternalSystem-NEW/Legacy/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.IsSingleInstanceCodeunitWithGlobalVars(ICodeunitTypeSymbol codeunitTypeSymbol)\r\n   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.ClearCodeunit(OperationAnalysisContext ctx)\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 766\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1102'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by Arthurvdv** [comment]
@tscottjendev, I've possible found another bug which could resolve this issue. If you have the time to verify this again, that would be much appreciated!

New updated prelease version available: [v0.30.6](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.6).

**Comment by tscottjendev** [comment]
Sorry, looks like the same error
[{
	"resource": "/c:/Repos/Jendev/JI-InternalSystem-NEW/Legacy/app.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AD0001",
	"severity": 4,
	"message": "Analyzer 'BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.IsSingleInstanceCodeunitWithGlobalVars(ICodeunitTypeSymbol codeunitTypeSymbol)\r\n   at BusinessCentral.LinterCop.Design.Rule0032ClearCodeunitSingleInstance.ClearCodeunit(OperationAnalysisContext ctx)\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 766\r\n   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\\a\\_work\\1\\s\\source\\Prod\\Microsoft.Dynamics.Nav.CodeAnalysis\\DiagnosticAnalyzer\\AnalyzerExecutor.cs:line 1102'",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by Arthurvdv** [comment]
Hooray, I've managed to find a possible repo scenario.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/32f8a5b6-9fc0-462a-b538-7705d023581d)

Again a new updated prelease version available: [v0.30.6](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.6). Hoping that I've now really resolved the issue 🤞 Is the third time really lucky charm here?

**Comment by tscottjendev** [comment]
That seems to have resolved it.  Thank you.

**Comment by Arthurvdv** [comment]
Awesome! :-)
