### ISSUE TITLE
LC0032 ClearAll() - Warning should not be raised when the codeunit is used in itself

### ISSUE THREAD

**Issue by ZepposBE** [StefanMaron/BusinessCentral.LinterCop#353]
Hi,

I'm facing the following issue:
I'm using a singleinstance codeunit and I have a procedure to clear all the stored data.
The ClearAll() in the example code below is raising the LC0032 error, which I understand since the [LC0032](https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/305) was created.
There should be an exception though for when the singleinstance codeunit that is found is the same as the codeunit itself.
These are rare occasions, and I can pragma these specific cases with a comment for now, but would be useful if the exception could be added to the warning. 

```AL
codeunit 50000 "My Single Instance Codeunit"
{
    EventSubscriberInstance = Manual;
    SingleInstance = true;

    var
        MySingleInstanceCodeunit: Codeunit "My Single Instance Codeunit";
        myBoolean: Boolean;
        myDecimal: Decimal;

    #region ClearEverythingThatIsStored
    internal procedure ClearEverythingThatIsStored()
    begin
        ClearAll(); // LC0032 warning for codeunit itself --> exception?
    end;
    #endregion ClearEverythingThatIsStored

    #region DoSomething
    internal procedure DoSomething(): Decimal;
    begin
        // Just some code
        if BindSubscription(MySingleInstanceCodeunit) then
            if myBoolean then
                exit(myDecimal);
    end;
    #endregion DoSomething

// EventSubscriber that is only active when this codeunit is Bound.
}
```

**Comment by Arthurvdv** [comment]
You're absolutely right, thank you for raising an issue here.

I've added this as an excluding to the rule. A new prelease [v0.30.6](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.6) is available which should resolve this.
