### ISSUE TITLE
Add Refactoring Help for Rule LC0029

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#359]
I do like the new Rule `Use CompareDateTime method in Type Helper codeunit for DateTime variable comparisons.`, but the wiki lacks some kind of instruction on how to replace the previous code.

I'd suggest something like to following:

Replace 
```al 
if (FirstRecord."DateTimeField" <> SecondRecord."DateTimeField") then
  ; //Do Magic if DateTime Fields are different
```

with

```al
if (TypeHelper.CompareDateTime(FirstRecord."DateTimeField",  SecondRecord."DateTimeField") <> 0) then
  ;  //Do Magic if DateTime Fields are different
```

**Comment by Arthurvdv** [comment]
Great suggestion!

I liked your example, so I've copy/paste it over to the wiki [LC0029](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0029).
