### ISSUE TITLE
LC0003/LC0005 false positive in parameters

### ISSUE THREAD

**Issue by ChristianHovenbitzer** [StefanMaron/BusinessCentral.LinterCop#362]
I found another false positive. I've tested this with a few diffferent object types so this should be related to being a parameter.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/91181840/4fc23aca-7910-4d1f-a9e9-667379946897)

**Comment by Arthurvdv** [comment]
Resolved in the (pre)release version [v0.30.7](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.7).

**Comment by Arthurvdv** [comment]
I was a bit to quick on thinking this was already resolved in the previous prerelease version.

Now a new prerelease version available [v0.30.7](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.7) which should resolve this issue.
