### ISSUE TITLE
LC0012 and Fully Qualified Object

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#380]
I am adding namespaces to some existing code.  I am getting this message

> Wrong Parameter detected. Select the correct object with "Page::" instead.
for this code
```
if Page.RunModal(Page::System.Reflection."Fields Lookup", Field) = Action::LookupOK then begin
  //Do something
end;
```
If I just have `using System.Reflection;` then it is fine.  The fully qualified reference would seem to be the issue.

**Comment by Arthurvdv** [comment]
The move to namespaces requires some adjustments here and there in the LinterCop, thank you for reporting this one!

Should be resolved in the (pre)release version of [v0.30.8](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.8).
