### ISSUE TITLE
Check for: IDs Instead of Names

### ISSUE THREAD

**Issue by aptMattKoe** [StefanMaron/BusinessCentral.LinterCop#4]
There is no good reason to use an ID as SourceTable or in variables, parameters instead of the Names.

**Comment by StefanMaron** [comment]
Would you mind to test this rule? 😎
Otherwise I would close this issue in a few days

**Comment by ChristianHovenbitzer** [comment]
The rule seems to trigger on every property with a number in it. This includes:
- Descriptions
- Tooltips
- Captions
- DecimalPlace
- Width

**Comment by aptMattKoe** [comment]
I've tested it and it works for me! :) thanks!

**Comment by aptMattKoe** [comment]
> The rule seems to trigger on every property with a number in it. This includes:
> 
> * Descriptions
> * Tooltips
> * Captions
> * DecimalPlace
> * Width

Could you take a screenshot? My Tests are not doing this.

**Comment by StefanMaron** [comment]
I think I fixed it meanwhile 😜 
Sorry I forgot to mention. 

Anyways. there are still issues:

- numbers in object name should not trigger this warning
- direct id usage in like `codeunit.Run(1)` should trigger this warning

**Comment by StefanMaron** [comment]
Numbers in Object Names should not trigger the warning anymore. 
direct usage of codeunit.Run(1) should be a separate rule I think

**Comment by ChristianHovenbitzer** [comment]
Codeunit Permissions falsely trigger warnings
![image](https://user-images.githubusercontent.com/91181840/134663137-3e867c3c-cead-46e6-94b2-e2a6cdcbc0cf.png)

**Comment by StefanMaron** [comment]
Good catch, will look into this later 👍

**Comment by StefanMaron** [comment]
Should be fixed with version 0.7
