### ISSUE TITLE
LC0039 support for DrillDownPageId and LookupPageId

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#401]
Sometimes pages have very similiar names and by accident the wrong page is set for the property DrillDownPageId  and LookupPageId.

is there any chance to get this new rule working for those two properties?

**Comment by Arthurvdv** [comment]
The (pre)release version [v0.30.9](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.9) now checks for both DrillDownPageId and LookupPageId parameters in table(extension) objects. Thank you for the suggestion! 

The documentation [DrillDownPageID Property](https://learn.microsoft.com/en-us/previous-versions/dynamicsnav-2018-developer/DrillDownPageID-Property#applies-to) referes that this property also can be set on a Page Fields. I can't remember using this anywhere, do we also need to check also on something there? 🤔

**Comment by NAVFreak** [comment]
@Arthurvdv  *cough*
I think I got an issue related to this.
Suddenly our pipelines started to fail with error related to LC0039
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/34970096/889a0564-522e-4006-a700-bbe999efd909)

And it seems to be v0.30.9 that does it
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/34970096/d8baaa0c-43c5-4fa8-9547-54e625781f16)

Somehow I can't reproduce it locally. Even though I just ticked these settings
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/34970096/c0ab9f7c-59c8-4256-a3d2-bbe284b8a5bd)

**Comment by NAVFreak** [comment]
NVM!
When I looked clooser I realised that I was fooled by the first object that I looked into. The lookup object doesn't have the same source table!
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/34970096/e2348737-85de-40b5-a9f6-2a0205e9b2c7)

The other objects are quite clear!
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/34970096/9943348d-dd79-4795-b447-b9b0945ae1a7)

I must say that this new rule update is really nice!
Now I'm off to pull some developers ears! 😈

**Comment by Arthurvdv** [comment]
@NAVFreak Great to hear that the new rule is helpfull :-)

**Comment by Arthurvdv** [comment]
Thanks for the feedback. For now I will not expand the rule on Page Fields for this, until we have a example with a better understanding what the rule should do on that.

> To be honest I would set this rule to a warning by default.

The default severity is already set to the level of warning? 🤔 At the moment [v0.30.9](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.9) is in state prelease, so you only get there when running the prelease version of the LinterCop.
