### ISSUE TITLE
LC0004 false positives (workspaces)

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#416]
Scenario:

- App A has a table A **without** "LookupPageID" and "DrilldownPageID" 
- App A has a listpart page A for table A

LC0004 is not raised when opening app A. (OK)

- App B has a dependency on App A
- App B has a **list** page B for table A
- A workspace exists with App A and B

LC0004 is raised when opening the workspace (NOK)

`warning LC0004: Property "LookupPageID" and "DrilldownPageID" must be filled in table "A" because it is used in page "B" (list)`

The warning should only be raised for tables / pages part of the **current** app. Pages from apps higher in the dependency tree should be excluded from the rule.

**Comment by Arthurvdv** [comment]
I've modified this rule and this should be resolved in the (pre)release version of [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10).

**Comment by Arthurvdv** [comment]
The version [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) of the LinterCop is now released. If would you still encounter this issue feel free to reopen this one.
