### ISSUE TITLE
LC0003 fails on "NVT Core Install Codeunit"

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#43]
Seems to be a false report 

CoreInstall: Codeunit "NVT Core Install Codeunit";

![image](https://user-images.githubusercontent.com/25268332/134907398-07a799d2-781f-4832-afe4-725ff5cf413f.png)

**Comment by StefanMaron** [comment]
Should be fixed in latest version

**Comment by StefanMaron** [comment]
Should be fixed in latest version

**Comment by StefanMaron** [comment]
Should be fixed in v0.14
