### ISSUE TITLE
Error message in rule 39 and 48

### ISSUE THREAD

**Issue by Axarath** [StefanMaron/BusinessCentral.LinterCop#441]
I have similar error messages in another extension. But version 0.30.10 did not fix it.

Analyzer 'BusinessCentral.LinterCop.Design.Rule0039ArgumentDifferentTypeThenExpected' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0039ArgumentDifferentTypeThenExpected.AnalyzeSetRecordArgument(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 766
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'

Analyzer 'BusinessCentral.LinterCop.Design.Rule0048ErrorWithTextConstant' threw an exception of type 'System.InvalidCastException' with message 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.BoundCall' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.IConversionExpression'.
   at BusinessCentral.LinterCop.Design.Rule0048ErrorWithTextConstant.AnalyzeErrorMethod(OperationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteOperationAction>b__1() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 766
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'

**Comment by Arthurvdv** [comment]
Any chance you have a small code sample that generates these errors?

**Comment by Axarath** [comment]
I'm not sure which part of the code generates it. And the project itself is quite big... I don't know how to hande it.

**Comment by Arthurvdv** [comment]
There's now easy way that I know of to find which object causes the error. If possible you could remove parts/modules of the project until you found the object, which can be a time consuming process.

I think I have a solution for LC0048 rule which is now in the updated prelease [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) version of the LinterCop.
On the LC0039 I'm unsure where the NullReferenceException could be and would be very helpful if you have a repo on that.

**Comment by Arthurvdv** [comment]
> I have achieved that LC0048 error disappeared

If you can narrow it down to the single file which causes this error that would be great!

**Comment by Arthurvdv** [comment]
@Axarath Did you by any chance find the source of these errors?

**Comment by Axarath** [comment]
@Arthurvdv Sorry Arthur, it is not so easy to identify source of error. Maybe during the Christmas time I can find more time for digging :-),

**Comment by jwikman** [comment]
@Arthurvdv, I believe that cases like this was the reason that Stefan added the [LC0000](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0000) rule. We had an issue some year ago where that helped us identify the source code that made the rule crash.

But I think that you'd need to add some try/catch around the rule having issues and use the info from the exception to emit LC0000 with meaningful troubleshooting information. Check how it is done in LC0023, just found out that it was still there. 🙂

**Comment by Arthurvdv** [comment]
> I believe that cases like this was the reason that Stefan added the [LC0000]

@jwikman, that's a good idea! I'll try to have a look but can take a few days during the holiday season.

**Comment by Axarath** [comment]
@Arthurvdv 

Rule 39:

    local procedure EditNavPassword()
    var
        SetPassword: Page "Password Dialog";
    begin
        Rec.TestField("User Name");

        CurrPage.SaveRecord();
        Commit(); //Save current changes before run aditional setup

        UserSecID.SetCurrentKey("User Security ID");
        UserSecID.SetRange("User Security ID", Rec."User Security ID");
        SetPassword.SetRecord(UserSecID);
        SetPassword.SetTableView(UserSecID);
        if SetPassword.RunModal() = Action::OK then
            CurrPage.Update(false);
    end;

Issue is in SetRecord and SetTableView method on the page. Rules correctly identified that somthing is wrong. Page itself is not associeted with any record but SetRecord and SetTableView try to send some :D.

**Comment by Axarath** [comment]
@Arthurvdv 

Rule 48:

                        ClearLastError();
                        if Codeunit.Run(Codeunit::ItgProcessDCW1) then
                            CurrPage.Update(false)
                        else
                            Error(GetLastErrorText);

Issue is caused by this last Error message.

**Comment by Arthurvdv** [comment]
> Page itself is not associeted with any record but SetRecord and SetTableView try to send some :D.

This was indeed what causing the problem.
I hadn't considered the possibility with these methods on a page without a SourceTable property.
This is now fixed in the (pre)release [v0.30.11](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.11) version of the LinterCop.

> Issue is caused by this last Error message.

```AL
Error(GetLastErrorText);
Error(GetLastErrorText());
```
Apparently the compiler handles these statements differently 🤯 (with and without the brackets).
This is now fixed in the (pre)release [v0.30.11](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.11) version of the LinterCop.


@Axarath , thank you for providing these examples, this was helpful to create a repo (and thank you @jwikman for the LC0000 suggestion).

I do have a question: Is this "Password Dialog" a special page, or should we always raise a rule explaining that the page has no SourceTable and that the method SetRecord and SetTableView shouldn't be there?

**Comment by Axarath** [comment]
@Arthurvdv 

I think it should always raise a rule explaining that the page has no SourceTable and that the method SetRecord and SetTableView shouldn't be there.

**Comment by Arthurvdv** [comment]
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/be4f557f-6bbd-43bf-8d01-b4c4a6c4d72b)

A new rule is added to the (pre)release [v0.30.11](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.11) version of the LinterCop!
