### ISSUE TITLE
LC0048 - Exclude blank errors

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#445]
We often want to halt a process (open page, ...) on purpose and halt the transaction (without actually showing a message to the user) by raising an error('').
I don't see the need why those should be converted to ErrorInfo / labels?
Maybe exclude 'Error('')' from the rule?

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/25268332/231db345-7f22-419f-8c55-990463065e93)

**Comment by Arthurvdv** [comment]
Thanks for reporting, this is indeed a false positive and should be resolved in the updated prelease [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) version of the LinterCop.
