### ISSUE TITLE
LC0044 - False positives when using SkipFieldsNotMatchingType

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#454]
I don't think that LC0044 should be triggered when the `TransferFields()` has been called with `SkipFieldsNotMatchingType` parameter set to `true` (Docs: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-transferfields-table-boolean-boolean-method)

I get LC0044 reported when I use `MyNewTable.TransferFields(MyOldTable, true, true)` in my upgrade code where I migrate data from an old table to a new one (with an updated Primary Key). In this case I use the `SkipFieldsNotMatchingType` parameter and handles the conflicting fields manually.

Since `SkipFieldsNotMatchingType` is very explicit, I think it is reasonable that this parameter could be added as an exception for LC0044.

Thoughts?

**Comment by Arthurvdv** [comment]
Makes perfectly sense, the rule should check for this parameter.

The updated (pre)release version [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) should now not raise when you set the SkipFieldsNotMatchingType parameter to true.

**Comment by jwikman** [comment]
Thanks @Arthurvdv,

Tested with `SkipFieldsNotMatchingType` set to both `true` and `false` and not set at all - And the rule works just as I expect it to do now! 👍
