### ISSUE TITLE
LC0003 fails on lower case object names

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#46]
Reading the message 

_Do not use an Object ID for properties or variables declaration. Use NVT Electronic Document Setup instead._

![image](https://user-images.githubusercontent.com/25268332/134927551-d8fbe26e-d3d7-4199-a6de-c879322ba855.png)

I would expect an **object ID** being used, that needs replacements.

![image](https://user-images.githubusercontent.com/25268332/134927523-dbb3f248-3e72-427c-a8b0-d7274d808ab2.png)

However, the object **name** is used, but the casing is not respected (it should have been written as 'NVT Electronic Document Setup' instead). For me this seems like an invalid candidate for the LC0003 rule and fits more the LC0005 rule (which we've excluded)

**Comment by StefanMaron** [comment]
Should be fixed in v0.14
