### ISSUE TITLE
LC0044 - Transferfields for Job / Project - BC24 - New Table Pairs

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#481]
BC24 will introduce new Tables that will use TransferFields:

```
new Tuple<string, string>("Job", "Job Archive"),
new Tuple<string, string>("Job Task", "Job Task Archive"),
new Tuple<string, string>("Job Planning Line", "Job Planning Line Archive"),
new Tuple<string, string>("Comment Line", "Comment Line Archive"),
```

Check out `codeunit 5139 "Job Archive Management" ` for details.

**Comment by Arthurvdv** [comment]
Thank you for reporting these upcoming entities, they will be added in the version [v0.30.11](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.11) of the LinterCop.

Tagging @tinestaric in case these aren't already in the CompanialCop.
