### ISSUE TITLE
LC0025 - Update Rule Title

### ISSUE THREAD

**Issue by ans-bar-bm** [StefanMaron/BusinessCentral.LinterCop#484]
The current title / message `Procedure must be either local or internal.` at a quick glance feels a bit lacking or even confusing at times ("why should this procedure which is clearly referenced in that other extension be local?").

Updating the wording to something like `Procedure must be either local, internal or define a documentation comment.` might be a bit clearer on the intent of the rule (without having to read the detailed rule description in the wiki).

**Comment by Arthurvdv** [comment]
Thank you for reporting this. I now see that the current description can be confusing indeed. The documentation comment part is later added I believe, where the description hasn't been adapted to that change.

In the (pre)release version of [v0.30.11](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.11) of the LinterCop the rule will have the description you've suggested.
