### ISSUE TITLE
LC0040 ModifyAll false positive?

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#510]
I am getting the warning: 

> Explicitly set the RunTrigger parameter on build-in methods.

when I have code like this:
`
Rec.ModifyAll(Billed, false);
`
Unless I miss understand the rule, this should not raise a warning.

**Comment by pri-kise** [comment]
`ModifyAll` has three paramters.
The third optional paramter is the runtrigger
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-modifyall-method

**Comment by tscottjendev** [comment]
DOH!
