### ISSUE TITLE
Rule0033AppManifestRuntimeBehind warning

### ISSUE THREAD

**Issue by JacobVanAchter-esc** [StefanMaron/BusinessCentral.LinterCop#524]
Hi,

For every project i get the following warning from Lintercop. I tried reinstalling, manually installing. Setting the execution Policy.

Analyzer 'BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index') at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument) at System.Linq.Enumerable.ElementAt[TSource](IEnumerable1 source, Int32 index)
at BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind.FindValueOfFirstValueLessThan(SortedList2 sortedList, Version version) at BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind.CheckAppManifestRuntime(CompilationAnalysisContext ctx) at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass48_1.<ExecuteCompilationActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 618 at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable1 info) in D:\a_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'`

**Comment by Arthurvdv** [comment]
Can you share a small example project which creates this error?

**Comment by Arthurvdv** [comment]
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/799f5eee-2694-49c4-93b1-f3fab69be6bb)

I think I have found a possible repo, could you share your app.json file to confirm my hypothesis?

**Comment by JacobVanAchter-esc** [comment]
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/78732337/f892ea4d-1736-476b-add9-87ccb7c28829)
[ALProject1.zip](https://github.com/StefanMaron/BusinessCentral.LinterCop/files/14086480/ALProject1.zip)
I attached a small sample project

**Comment by Arthurvdv** [comment]
Found the issue!

```json
"platform": "1.0.0.0",
"application": "1.0.0.0",
```

Setting both of them lower then `12.0.0.0` causes this error, because that isn't a valid version; https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-choosing-runtime#currently-available-runtime-versions.

May I ask why both of them have this value?

_Best pratice_ would be to set both of them to the minimal version of Business Central that the App need to work.

**Comment by Arthurvdv** [comment]
I've resolved this error in the (pre)release version of [v0.30.12](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.12) of the LinterCop,

**Comment by Arthurvdv** [comment]
The [v0.30.13](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.13) version of the LinterCop is now released, where I believe this issue is now resolved. If you still encounter issues, feel free to reopen this issue (or create new one).
