### ISSUE TITLE
LC0045 Add explanation to wiki

### ISSUE THREAD

**Issue by JohnnyUndercover** [StefanMaron/BusinessCentral.LinterCop#532]
Can someone explain why 0 should only be used for empty values and add this info to the wiki?

**Comment by Arthurvdv** [comment]
I've updated the documentation of the [LC0045](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0045) rule to add explanation on why this rule could be helpful.

Hopefully this makes the intent of this rule more clear now. If you have suggestions or feedback on this please let me know.

**Comment by JohnnyUndercover** [comment]
Thank you. This is exactly what i was missing.
