### ISSUE TITLE
Implement LC0024 on trigger declarations

### ISSUE THREAD

**Issue by Aize-S** [StefanMaron/BusinessCentral.LinterCop#537]
"LC0024: Procedure declaration should not end with semicolon." works on procedures. But it doesn't work on triggers. I came across a number of OnValidate triggers in a project where the declaration ended wit a semicolon. I've also checked OnInsert trigger and it doesn't go off there either.

I think it would make sense to create a check on trigger declarations as well.

**Comment by Arthurvdv** [comment]
The (pre)release version [v0.30.14](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.14) of the LinterCop will now also raise the LC0024 diagnostic on trigger declarations.

**Comment by Arthurvdv** [comment]
The [v0.30.14](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.14) version of the LinterCop is now released, where I believe this issue is now resolved. If you still encounter issues, feel free to reopen this issue (or create new one).
