### ISSUE TITLE
LC0016: exception needed for grid controls

### ISSUE THREAD

**Issue by Pazzakara** [StefanMaron/BusinessCentral.LinterCop#548]
Although page controls of type grid can tecnically have a caption property, the caption is never displayed on the UI.
Therefore the caption property should not be mandatory for grids.

**Comment by Arthurvdv** [comment]
Can you help me with small .AL example?

I've tested with an example [from here](
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-arrange-fields-in-rows-and-columns-using-gridlayout-control) which doesn't raises the LC0016 it seems?

**Comment by Pazzakara** [comment]
hm.. if i copy the code of the link you have posted, I get a lot of LC0016 warnings including line 11 which is `grid(MyGrid)`.
If this is useful: I'm using BusinessCentral.LinterCop Version: 0.1.6

Here is another example I have created
[ExamplePage.txt](https://github.com/StefanMaron/BusinessCentral.LinterCop/files/14406711/ExamplePage.txt)

**Comment by Arthurvdv** [comment]
Your example was a perfect help and indeed raised a false positive on Grid control.

This should now be resolved in the (pre)release version of [v0.30.14](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.14) of the LinterCop.

**Comment by Arthurvdv** [comment]
The [v0.30.14](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.14) version of the LinterCop is now released, where I believe this issue is now resolved. If you still encounter issues, feel free to reopen this issue (or create new one).
