### ISSUE TITLE
BCLinterCop vs AL-GO Experiences

### ISSUE THREAD

**Issue by dsaveyn** [StefanMaron/BusinessCentral.LinterCop#562]
I justed wanted to inform if anyone has experience with setting up BCLinterCop i.c.w. AL-GO? 

From what I've tested myself and [read](https://github.com/microsoft/AL-Go/issues/788) on the issues list of AL-GO I believe this is not working correctly. 

Also - if it would work - is there any way the version number of the BCLinterCop release should not be included in the URL and the latest release is always used? This would avoid modifications every time a new version is released.

**Comment by Arthurvdv** [comment]
I'm not (yet) familiar with the possibilities of AL-Go, where I mostly work in Azure DevOps myself.

It should work, lets continue this here: https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/519
