### ISSUE TITLE
LC0016 with SplitButton and Repeater Scope

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#587]
When having the [_ShowAs_](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-showas-property) property on an Action Group set to `SplitButton`, the _Caption_ property is not needed on the group. LC0016 handles this in a nice way.

But I just discovered that if an action inside a `SplitButton` Action Group has the [_Scope_](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-scope-action-property) set to `Repeater`, the _Caption_ is needed for the context menu on the line, otherwise an autogenerated caption i displayed in the context menu (in my example, the actions are promoted, hence the `Category_` prefixes):

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/23032645/427f69c2-1330-41c1-b9aa-e07eb95f4e49)

So, to my suggestion:
Add a new condition for LC0016, to require _Caption_ on Page Action Group if they have `SplitButton` specified and the action _Scope_ is set to `Repeater`. (Note that this should apply both to action groups in the promoted action area, as on regular action groups)

**Comment by Arthurvdv** [comment]
Thank you @jwikman for the detailed description and example, this was of great help!

This should now be resolved in the (pre)release version of [v0.30.20](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.20) of the LinterCop.

**Comment by jwikman** [comment]
Thanks @Arthurvdv!

**Comment by Arthurvdv** [comment]
Version [v0.30.20](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.20) of the LinterCop is now released.
