### ISSUE TITLE
Rule0033AppManifestRuntimeBehind - 'System.MissingMethodException'

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#590]
We receive the following warning in our Azure DevOps pipeline.

```
##[warning]warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind' threw an exception of type 'System.MissingMethodException' with message 'System.MissingMethodException: Method not found: 'Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.NavAppManifest Microsoft.Dynamics.Nav.Analyzers.Common.ManifestHelper.GetManifest(Microsoft.Dynamics.Nav.CodeAnalysis.Compilation)'.

##[warning]at BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind.CheckAppManifestRuntime(CompilationAnalysisContext ctx)
##[warning]at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass48_1.<ExecuteCompilationActionsCore>b__0() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 618
##[warning]at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1086'
```

We only have on PageExtension in this app, because this is our template app.
```al
pageextension 50000 "PTE CustomerListExt" extends "Customer List"
{
    trigger OnOpenPage();
    begin
        //Message('App published: Hello world');
    end;
}
```

Versions:
- Microsoft (R) AL Compiler version 12.7.14.63589
- Application Version: 23.5

**Comment by Arthurvdv** [comment]
Unfortunately the LinterCop is only compatible with the latest AL Languague version, currently v13.0.971907.

There was a [breaking change](https://github.com/StefanMaron/BusinessCentral.LinterCop/commit/3d906f7baa0e5c5279c633c474f57309e1428e09) between v12 and v13 of the AL Lanuage which is releated to the error exception you're experiencing right now.

If you are using Run-ALPipeline in your build pipelines you should also load the latest compiler from the marketplace. Add -vsixFile (Get-LatestAlLanguageExtensionUrl) to do so.

**Comment by pri-kise** [comment]
Okay . 
Good to know I haven't thought of something like that.

Adding this AL Language Issue for Reference: https://github.com/microsoft/AL/issues/7569

**Comment by pri-kise** [comment]
I've tested it with the Latest AL Language version.
Now it's working fine.
I will have to update our pipelines now, but at least it's working now.
