### ISSUE TITLE
Preview AL Language 14 - Unable to load Analyzer assembly

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#592]
I receive the following warning in my projects when using the Preview Version of the AL Language Extension.
```al
Unable to load Analyzer assembly c:\Users\kise\.vscode\extensions\ms-dynamics-smb.al-14.0.986719\bin\Analyzers\BusinessCentral.LinterCop.dll : File c:\Users\kise\.vscode\extensions\ms-dynamics-smb.al-14.0.986719\bin\Analyzers\BusinessCentral.LinterCop.dll was not found.
```
My settings.json:
```al
{
    "al.codeAnalyzers": [
        "${AppSourceCop}",
        "${CodeCop}",
        "${PerTenantExtensionCop}",
        "${UICop}",
        "${analyzerFolder}BusinessCentral.LinterCop.dll"
    ],
```

My Analyzer Folder Content:
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/56249171/f2c05c6d-10cb-4983-af1f-3a7d6d9d3327)

Is there anything that I could do?

**Comment by pri-kise** [comment]
I copied `BusinessCentral.LinterCop.next.dll` to `BusinessCentral.LinterCop.dll``and now it's working again, but I'm not a fan of this manual step.

**Comment by Arthurvdv** [comment]
This is unfortunately the expected behavior of the [VS Code extension](https://github.com/StefanMaron/vsc-lintercop).

When switching to the Pre-Release version of the AL Language you need to manually swap the .DLL file. This has always been this way. I'm not (yet) familiar with creating VS Code extensions, so I can't help you at this moment.

**Comment by rvanbekkum** [comment]
Could VS Code profiles help out with this somehow?

1. Have separate VS Code profiles, one that you use together with the stable version of the AL Language extension, another profile  in which you use the pre-releases of the AL Language extension
2. Then, it would be good if we could have a setting in the LinterCop VS Code extension to configure our preference of which .dll should be used, the `.next.dll` or the `.current.dll`

**Comment by Arthurvdv** [comment]
Working together with @StefanMaron to support multiple version of the AL Language.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/6fed8b24-71c0-419c-ac55-07acf80c085f)

I've did an overhaul of the build pipeline, to build against multiple version of the AL Language. The next step is to update the VS Code extension to retrieve the matching artifact based on the installed version of the AL Language in VS Code.

**Comment by Arthurvdv** [comment]
Good news!

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/f6e41071-d2e3-4a1d-93a1-1ff7fa56123c)

The combination of the new [v0.30.18](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.18) version of the LinterCop, combined with the new [0.1.7](https://marketplace.visualstudio.com/items?itemName=StefanMaron.businesscentral-lintercop) version of the VS Code now supports multiple version of the AL Language.

This works automatically on the background, where the VS Code extension grabs the version of the installed AL Language and then retrieves the a matching LinterCop .dll file.
