### ISSUE TITLE
LC0044 - Add support for extra transferfields from Base Application

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#600]
- Fix typo 'BankAccount' > 'Bank Account'
- Added transferfields support between 'Customer' > 'Customer Templ.'

```
codeunit 1381 "Customer Templ. Mgt."
...
CustomerTempl.TransferFields(Customer);
...
```

**Comment by Arthurvdv** [comment]
Thank you for raising this issue ánd providing a PR to resolve this.

I've merged this in the (pre)release version of [v0.30.18](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.18) of the LinterCop.
