### ISSUE TITLE
LC0005 doesn't work in XmlPost

### ISSUE THREAD

**Issue by guidorobben** [StefanMaron/BusinessCentral.LinterCop#609]
LC0005 doesn't check the fieldelement in an XmlPort.

tableelement(Item; Item)

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/11609736/a9313d23-cee0-44db-b2a1-c22e8f6257e6)

I would expect an warning for the two item lines (200, 212)

**Comment by Arthurvdv** [comment]
Thank you reporting this and should now be resolved in the (pre)release version of [v0.30.20](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.20) of the LinterCop.

**Comment by Arthurvdv** [comment]
Version [v0.30.20](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.20) of the LinterCop is now released.
