### ISSUE TITLE
NotBlank = TRUE is not working when you have a PK field which is based on a number series

### ISSUE THREAD

**Issue by janvtBE** [StefanMaron/BusinessCentral.LinterCop#620]
Hi,

We had some issues with rule LC0013: https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0013.

When you have a single PK field which is Text or Code and this field is filled in by a number serie, the NotBlank = TRUE is causing the following error:

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/74171877/76d1edd4-8d0f-49a6-9a95-5dfee1764c9f)

How we interpret this: the NotBlank property is executed first before the OnInsert trigger, where the code is to fill in a new number of the coupled number serie.

Has anyone had the same issue with this and how did you handled this? Putting the NotBlank to FALSE or something else? :)

Second question: is it an option to create a rule for this? Of course, how do you know when there is a number serie coupled to this field...

All input / other options are welcome :)

Thanks

**Comment by pri-kise** [comment]
We had the same issue on a customer project for those tables and disabled the LinterCop rule for those specific fields.

**Comment by Arthurvdv** [comment]
> We had the same issue on a customer project for those tables and disabled the LinterCop rule for those specific fields.

Strange, because the rule should consider if the the 'No. Series' pattern is there and then will not be raised? 🤔

**Comment by janvtBE** [comment]
@Arthurvdv the field "No. Series" was there, but had no tablerelation with "No. Series" table. But also after adding this to the field, it still raised the error:

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/74171877/c836f58d-4b39-4298-83a4-aa84ac86248c)

**Comment by Arthurvdv** [comment]
Seems that we have a bug, I'll have a look into this!

**Comment by Arthurvdv** [comment]
It seems I can't reproduce this problem and could use some help.

When I set the 'TableRelation = "No. Series";' to a field on the table, the diagnostic of the LC0013 isn't raised.

```AL
table 50100 MyTable
{
    fields
    {
        field(1; "No."; Code[20])
        {
            Caption = 'No.';
        }

        field(100; "No. Series"; Code[20])
        {
            Caption = 'No. Series';
            TableRelation = "No. Series";
        }
    }

    keys
    {
        key(PK; "No.")
        {
            Clustered = true;
        }
    }
}
```

**Comment by NKarolak** [comment]
@Arthurvdv 
I'm seeing LC0013 now suddenly as well, and I'm not aware of a recent code change on my side, unless it's the added `AllowInCustomizations` below - added due to LC0035. Or did the Linter Cop update?

Mind that my "No. Series" field looks slightly different, because IMHO the PK fields should always be set in a TableRelation to feed Where Used (new linter rule? ;-)):
```
        field(107; "No. Series"; Code[20])
        {
            AllowInCustomizations = Always; // <-- added recently due to LC0035
            Caption = 'No. Series';
            Editable = false;
            TableRelation = "No. Series".Code;
        }
```

**Comment by NKarolak** [comment]
@Arthurvdv I've just tested it: No, `AllowInCustomizations` has no influence.
But my `TableRelation = "No. Series".Code;` does have it!
If I set it to `TableRelation = "No. Series";`, then LC0013 vanishes :-)
Weird that the warning appeared so late without a code change on my side.

But it looks this is not the cause on @janvtBE's side, as per his [screenshot](https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/620#issuecomment-2128604344).

**Comment by Arthurvdv** [comment]
Thank you @NKarolak, you were right on including the PK field (Code) to the TableRelation would trigger a false positive.

Determining the table TableRelation to the "No. Series" includes some string comparison with quoting and unquoting string value. Could be that there's been some changes under the hood which influenced the behavior on this. I've changed the logic on the rule on this to provide a better handeling on this.

I'll create two new idea's in the Discussions based of the information in here:
* NotBlank on single field PKs false if there's a TableRelation = "No. Series" present on the table
* The PK fields should always be set in a TableRelation (to feed Where Used)

**Comment by Arthurvdv** [comment]
The version [v0.30.28](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.28) of the LinterCop is now the latest release. Could you verify if this is now working as expected? If this is the case, you may close this issue.

**Comment by NKarolak** [comment]
I'm not the issue creator - but for me, it's solved. Thanks!

**Comment by janvtBE** [comment]
Thanks @Arthurvdv for the fix: https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0067. I'll close this issue as resolved!
