### ISSUE TITLE
LC0016 raised on extension fields where base field uses CaptionML

### ISSUE THREAD

**Issue by ans-bar-bm** [StefanMaron/BusinessCentral.LinterCop#626]
I still have some extensions running on BC 14 (ugh) where all the BaseApp fields are still in C/AL with the CaptionML property.
If I now add any BaseApp field to a page via PageExtension i get the LC0016 warning "Caption is missing.":
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/155651932/d3a62888-eac4-4dda-a373-6729e6c55350)
I would expect the warning to not show as a caption is set on the base table field - just with the old property syntax.
I understand that adding the old CaptionML syntax to the "allowed" captions of the fields in my own app might not be wanted. In that case maybe there is an option to disable the warning for references to fields in other apps only (so only raise it on extended fields where the "owner" uses CaptionML)?

**Comment by Arthurvdv** [comment]
Thank you for raising this issue and also providing a PR for the solution.

This is now available in the (pre)release version of [v0.30.21](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.21) of the LinterCop and will be included in the upcoming release.

**Comment by Arthurvdv** [comment]
This should now be resolved in the release version of [v0.30.25](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.25) of the LinterCop.

**Comment by ans-bar-bm** [comment]
Did a quick test, worked for me. Thanks!
