### ISSUE TITLE
No artifact available for BusinessCentral.LinterCop.AL-13.0.1027618.dll

### ISSUE THREAD

**Issue by rvanbekkum** [StefanMaron/BusinessCentral.LinterCop#641]
Today a new AL Language extension / alc version was released, 13.0.1027618, but no LinterCop build is available for this build/version
We are currently using this in our build pipelines which complains that it cannot find the build.
I can imagine it is 'as simple' as re-running the LinterCop build pipeline to get the issue resolved?

But I also just want to ask your opinion on how we could best deal with this in our build pipelines? Perhaps we could just fall back on the `BusinessCentral.LinterCop.current.dll` file if this occurs, or just skip code analysis from LinterCop. Do you have other suggestions?

**Comment by Arthurvdv** [comment]
Damn, you're fast 😅 (I've noticed the update in VS Code just a few minutes ago).

We have a daily check for new releases, where the update was just after running the check for new versions it seems.

For pipelines at the moment I would advice to use the `BusinessCentral.LinterCop.dll` in combination with the latest release version of the AL Language on the Marketplace. I'm still searching for feasible solution in combination with the artifacts of Business Central (like Current, Next Minor, Next Major).

**Comment by rvanbekkum** [comment]
What's the difference between `LinterCop.dll` and `LinterCop.current.dll` in the artifacts by the way?
