### ISSUE TITLE
LC0044 false positive

### ISSUE THREAD

**Issue by dsaveyn** [StefanMaron/BusinessCentral.LinterCop#652]
In our opinion we are receiving a false positive on rule LC0044. We are moving a table from one app to another. The tables are exactly the same besides other suffixes in the field names (for some reason my colleague decided to add a suffix in our own tables). One table is obsoleted while the other isn't:

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/92365904/3b13482d-0ca8-4cf3-9af7-1db0472b382d)

Is this something that your are willing to fix?

**Comment by Arthurvdv** [comment]
I've given it some more thought, and don't see an thorough solution to handle a scenario like this.
