### ISSUE TITLE
[Question] How to compile repository code?

### ISSUE THREAD

**Issue by iwanscheidsnc** [StefanMaron/BusinessCentral.LinterCop#658]
I would like to compile the repository code locally. How do I know which ALLanguage version I have to use as dependency?

If I use the script LoadALLanguage.ps1 I get version 13.0.1027618, but I get compile errors:

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/141643457/73c31e8b-ac05-4c88-8518-4a10e90eba03)

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/141643457/9cf87304-6804-4c78-9a72-d831e013f69f)

Is there an instruction for development?

**Comment by rvanbekkum** [comment]
Typically/mainly the latest Visual Studio marketplace version of the AL Language extension.

But it might be that your rule needs to account for different versions of alc (as some methods are moved to different classes with newer versions of the alc .dlls) and then you might for example need to use preprocessor directives to account for that; and then you need other versions of alc as well.

**Comment by Arthurvdv** [comment]
Normally with the LoadALLanguage.ps1 script you should be able to locally compile the project. Which version of the .NET SDK do you have installed?

**Comment by iwanscheidsnc** [comment]
Thanks for the answers.

I have version 8.0.302 installed. Do I need the preview version 9?

**Comment by Arthurvdv** [comment]
Not sure what's going wrong.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/62726ec3-5bdb-4f90-8006-068c9439cdd1)

Are you compiling the project thought the VS Code command palette -> Tasks: Run Task -> build? (or build_dotnet)

**Comment by iwanscheidsnc** [comment]
I used the command "dotnet msbuild" in the terminal. But using the VS Code command palette -> Tasks: Run Task -> build and build_dotnet does not work too. I still get the error, that the AppSourceCopConfigurationProvider does not contain a definition for GetManifest.

**Comment by rvanbekkum** [comment]
Might have to do with these preprocessor directives in some of the rules:

```cs
#if ManifestHelper
            NavAppManifest manifest = ManifestHelper.GetManifest(ctx.Compilation);
#else
            NavAppManifest manifest = AppSourceCopConfigurationProvider.GetManifest(ctx.Compilation);
#endif
```

Depending on the version of AL the method is in a different class.

**Comment by Arthurvdv** [comment]
Can you try if you edit these preprocessor directives if this resolves your issue?

The example from above here could be edited to one single line:

```C#
NavAppManifest manifest = ManifestHelper.GetManifest(ctx.Compilation);
```` 

If this works, then you have to look into setting the FeatureFlags during the compiling. To support backwards compatibility to older versions we need to work with these preprocessor directives.

To compile to the current version, you need to provide specific FeatureFlags, for example: 

```powershell
dotnet build /p:FeatureFlags=#ManifestHelper
```

**Comment by iwanscheidsnc** [comment]
If I provide FeatureFlags I can compile the code, thanks for the help.
