### ISSUE TITLE
AD0001 in specific app.json

### ISSUE THREAD

**Issue by Arthurvdv** [StefanMaron/BusinessCentral.LinterCop#682]
### Discussed in https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/680

<div type='discussions-op-text'>

<sup>Originally posted by **SorenBogelund-ECIT** July  8, 2024</sup>
I have an issue with a specific app.json in a specific repository. The issue does not appear in other app.json files. For some reason 10 warnings are generated for no reason?
![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/169046245/8c486e3f-66fb-4c3a-b3e7-37464f42557e)
</div>

**Comment by Arthurvdv** [comment]
@SorenBogelund-ECIT, thank you for reporting this error. Not sure what's causing this at the moment, but I've added an check in the pre-release version of the LinterCop to identify the line of code responsible for this exception.

Could you switch to the pre-release version of the LinterCop look for a LC0000 diagnostic? Would be great if you could share a small code example so I could investigate this.

![image](https://github.com/StefanMaron/BusinessCentral.LinterCop/assets/44637996/b4d28698-32ed-4b75-bac1-30fd5099f298)

**Comment by Arthurvdv** [comment]
@SorenBogelund-ECIT, did you by any chance had the time to look into this?

**Comment by SorenBogelund-ECIT** [comment]
Hi Arthur

Do you mean like this?:

![image](https://github.com/user-attachments/assets/e716bd8f-ad97-4a83-b559-c92cbedda2c4)

**Comment by Arthurvdv** [comment]
I believe this needs to be a User Setting I've never try'ed as a workspace-setting, so not sure if this works.

![image](https://github.com/user-attachments/assets/85a579fc-16e1-43bf-ae9e-3884ae23cfba)

After setting this, you need to close all(!) VS Code windows and after that opening the AL project it will download the pre-release version of the LinterCop, where you should no longer have the error on the app.json, but on the specific line in the AL file.

You could also manually grab the BusinessCentral.LinterCop.dll file from the [releases](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases) and override this in the `%userprofile%\.vscode\extensions\ms-dynamics-smb.al-13.1.1065068\bin\Analyzers` folder. It should be the pre-release version [v0.30.28](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.28) of the LinterCop.

![image](https://github.com/user-attachments/assets/5581b5cc-e0a5-4667-9b7f-d4c385569bc8)

**Comment by SorenBogelund-ECIT** [comment]
Hi Arthur

It looks like, you are right, no errors:

![image](https://github.com/user-attachments/assets/17fd82ef-884a-47fd-bea7-4ca0467c2ec8)

 Thank for the tip about the Page Management codeunit. :)

**Comment by Arthurvdv** [comment]
The version [v0.30.28](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.28) of the LinterCop is now the latest release.
