### ISSUE TITLE
LC0004 - False Positive for Page with property SourceTableTemporary = true;

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#703]
I currently receive the warning `LC0004` for one table that isn't a table with temporary (historical reasons).
We have on list page for this table with the property `SourceTableTemporary = true;`.

This page is suggested for DrillDownPageId and LookupPageId.

This is a false positive, since you don't want to specify a Page with SourceTableTemporary as DrillDownPageId in the normal cases.

**Comment by Arthurvdv** [comment]
Good catch, in this case you're right and the rule shouldn't raise a diagnostic.

This should now be resolved in the (pre)release version of [v0.30.29](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.29) of the LinterCop.
