### ISSUE TITLE
LC0005 - casing on datatype

### ISSUE THREAD

**Issue by ChristianHovenbitzer** [StefanMaron/BusinessCentral.LinterCop#73]
LC0005 does not trigger on datatypes. This applies to variables and parameters. 
![image](https://user-images.githubusercontent.com/91181840/139825876-3f69c37a-eeb1-4508-8606-6996e31f3f28.png)

**Comment by StefanMaron** [comment]
I think this should get the job done
![image](https://user-images.githubusercontent.com/24838311/141004681-9c2200fe-0f73-4299-b6f6-031b427d9af7.png)
