### ISSUE TITLE
LC0068 does not handle fully qualified table names

### ISSUE THREAD

**Issue by glynge** [StefanMaron/BusinessCentral.LinterCop#730]
Hi

Thank you for your great work on LinterCop.

If you use fully qualified table names for tabledata in your Permissions property, LC0068 will give you a false positive: '...info LC0068: The current object is missing permission "x" for tabledata "y"'

It works perfectly if you use the "using" keyword for the namespace instead of using the fully qualified object name.

Expected: 
As fully qualified object names are valid, I would expect LC0068 to also handle it correctly :-).

**Comment by StefanMaron** [comment]
Thanks, I missed that.

**Comment by StefanMaron** [comment]
Please retest with the most recent pre-release version

**Comment by glynge** [comment]
I can confirm it works here now (with latest pre-release version).
Thank you for your great support and for this fantastic Code Cop :-)
