### ISSUE TITLE
LC0031 - ReadIsolation - Description is ambiguous

### ISSUE THREAD

**Issue by ChristianHovenbitzer** [StefanMaron/BusinessCentral.LinterCop#731]
the description for this rule states "Set ReadIsolation property instead of LockTable method." but you can set the ReadIsolation like "Rec.ReadIsolation()" and reset the actual isolation level.

I suggest the description to be changed to "Set ReadIsolation(IsolationLevel::UpdLock) property instead of LockTable method."

**Comment by Arthurvdv** [comment]
Long overdue, but I finally had some time today to take a look at this.

I've updated the diagnostic in VS Code to `Use ReadIsolation(IsolationLevel::UpdLock) instead of LockTable()`, hoping this will resolve the ambiguity.

**Comment by Arthurvdv** [comment]
With the release of [v0.31.2](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.2) the ambiguous dagnostic description is changed. Thank you for the suggestion on this!
