### ISSUE TITLE
LC0010 wiki - Invalid link

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#736]
The [LC0010 wiki](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0010) contains an invalid link to LinterCop.json

**Correct link**
_https://github.com/StefanMaron/BusinessCentral.LinterCop/blob/master/BusinessCentral.LinterCop/LinterCop.json_

**Comment by Arthurvdv** [comment]
Thanks! I've updated the wiki and the link should work now again.
