### ISSUE TITLE
Document all rules

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#77]
(a spin off from #48)

I believe that all the rules deserves their own .md file that documents them.

Our goal with this is actually to don't have any use of your CodeCop, because all code is perfect already 😉

This documentation would help developers to understand why a warning appears and what to do to resolve them (and avoid them in the future). 

As inspiration for headers in these files (not all for every rule, but one or more per rule):
- Description
- Bad code example
- Good code example
- Reason for the rule
- How to fix this diagnostic?
- Code examples triggering the rule
- Code examples not triggering the rule

Microsoft is using all of above in different rule descriptions on MS Docs.

**Comment by rvanbekkum** [comment]
It would be nice if the diagnostics can link to a wiki page that explains the diagnostic. 😊

![image](https://user-images.githubusercontent.com/7383241/142455214-6e4a64a9-0a4c-4bd6-b619-8772fdb08c07.png)

**Comment by rvanbekkum** [comment]
I think you could also link to your [wiki](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki) from the README as I think a lot of people will not be aware that you (are planning to) document the rules there.

**Comment by StefanMaron** [comment]
All done in prerelease.

**Comment by jwikman** [comment]
Great @StefanMaron, this is sooo good! 👍
