### ISSUE TITLE
LC0054 - Prefix

### ISSUE THREAD

**Issue by MikkelJensenECIT** [StefanMaron/BusinessCentral.LinterCop#784]
This rule does not work if the interface has a prefix.

Example:
```al
interface EDK_IExample
{
}
```

**Comment by MikkelJensenECIT** [comment]
I don't have AppSourceCop enabled though

**Comment by MikkelJensenECIT** [comment]
Is it possible to do the same with the PerTenantCop?

**Comment by StefanMaron** [comment]
I always recommend to use all cops.

I have created rulesets to make them work in combination

https://github.com/StefanMaron/RulesetFiles

**Comment by Arthurvdv** [comment]
> I don't have AppSourceCop enabled though

No need for the AppSourceCop itself, but I need the file in the root of the workspace to determine the affix.

**Comment by Arthurvdv** [comment]
> The AppSourceCop itself doesn't need to be enabled. We're only using the config file to retrieve the affixes, avoiding duplicate configuration in case of AppSource development.

I've added this to the documentation (wiki) for this rule. @MikkelJensenECIT, were you able to get it working?
