### ISSUE TITLE
Suggestion: IsHandled var check

### ISSUE THREAD

**Issue by TKapitan** [StefanMaron/BusinessCentral.LinterCop#792]
I have a new suggestion to add a warning if an event has an IsHandled variable without var. I missed this in the code review, and the only way to change it for the published app is to make the event obsolete and create a new one. A warning would prevent this issue.

**Comment by ChrisBlankDe** [comment]
Already suggested in Discussion https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/201

**Comment by Arthurvdv** [comment]
Let's continue this in the discussion @ChrisBlankDe has referenced.
