### ISSUE TITLE
Settings to configure warnings and errors

### ISSUE THREAD

**Issue by mrabus** [StefanMaron/BusinessCentral.LinterCop#9]
Right now, the linter is creating warnings. Is there some way to make them errors or even better, can we define which issues should be errors and which should be warnings?

**Comment by StefanMaron** [comment]
Yes, by custom rule set, just like you do with the MS code rules

**Comment by mrabus** [comment]
Didn‘t know that works for custom linters too. Thanks and case closed

**Comment by StefanMaron** [comment]
pragmas do also work ;)
