### ISSUE TITLE
LC0013 - improvements

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#92]
Really nice to find all those places where a `NotBlank` has been missed! 👍

But two things:
- I think that an explicit `NotBlank = false` should suppress this warning. In that way we could allow blank PK for the setup tables. Right now I get a lot of warnings about NotBlank is missing from all setup tables, and I want to avoid pragmas as long as possible and rather have explicit declarations...
- A small spelling error: "Tables with a single field PK sould have NotBlank set to true" are missing an "h" in "should" :)

**Comment by StefanMaron** [comment]
I like the Idea! I did not want to do complicated parsing of objects to identify possible setup tables. 
But I agree, an explicit `NotBlank = false` should also satisfy the rule.

**Comment by StefanMaron** [comment]
New release is out.

**Comment by jwikman** [comment]
Blizing fast today! 😁

But It seems as if you just killed LC0013... I don't get LC0013 on any table now...

**Comment by StefanMaron** [comment]
I also updated the wiki page for this rule   
https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0013

**Comment by StefanMaron** [comment]
> Blizing fast today! 😁
> 
> But It seems as if you just killed LC0013... I don't get LC0013 on any table now...

hmm. For me it still works:  
![image](https://user-images.githubusercontent.com/24838311/141970851-0fb4697d-7209-4035-a13b-c4c6f7bef90d.png)

**Comment by jwikman** [comment]
> I also updated the wiki page for this rule https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0013

Nice, I hadn't seen those pages yet! Maybe with should proceed and close #77 then?

**Comment by jwikman** [comment]
> > Blizing fast today! 😁
> > But It seems as if you just killed LC0013... I don't get LC0013 on any table now...
> 
> hmm. For me it still works

hmmm, I'll investigate some more

**Comment by StefanMaron** [comment]
> > I also updated the wiki page for this rule https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0013
> 
> Nice, I hadn't seen those pages yet! Maybe with should proceed and close #77 then?

Yes, thats the plan. But still some documenting to be done

**Comment by jwikman** [comment]
Hmmm, after a few more calls to "Reload Window" and "LC: Download Linter Cop" it kicked back in again - And now it works just great!
