### ISSUE TITLE
Preview release of dll

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#94]
The auto deployment of the Linter Cop DLL is really neat!

But when deploying fixes it might be a bit to easy to deploy a fix with regression issues or that a new rule that is not yet 100% perfect creates zillions of new warnings that will just confuse users until they understand the rule completely.

So I suggest that a new boolean setting is added to the VSCode extension, `Install Preview releases`, or similar.
If this setting is active, the dll should be downloaded from another location - to where you deploy preview versions of the dll.

In that way you can get things tested out by a group of volunteers and get feedback before deploying to all users.

I would always have the preview release installed... 😉

Thoughts?

**Comment by rvanbekkum** [comment]
That would be really nice. When there are errors/false positives in these code analyzers, then it becomes very difficult to distinguish real warnings from errors and makes the LinterCop inoperable.
Would be nice to have preview versions for which we could provide you (and others) with feedback. 😊

**Comment by StefanMaron** [comment]
100%  
But to prepare for this, I will need to implement a branching strategy and need to adjust the pipeline.  

Another thought I had, was to introduce new rules as `info` or even as `disabled` first.  
Testers can activate the rule via ruleset and report any issues.
That would work with less overhead and preparation.

**Comment by jwikman** [comment]
I would vote for a new branching strategy with a "preview" branch.

The other approach would work on new rules, but for changes in existing rules you would still risk to mess with a lot of users if a bug sneaks in.

I believe that the majority of developers would value stable and correct (now what that is 😉) code cop rules higher than smoking new changes and additions.

But for some people, as myself, like to work with new things and want to help to make our developer experience the best it can be - and for those, some kind of "preview" feature would be great.

**Comment by StefanMaron** [comment]
I will think about how to change branching strategy and pipeline, as well as a possibility to get auto update for preview releases 👍

**Comment by StefanMaron** [comment]
I made changes to the pipeline, branches and to the vs code extension. 

add `"linterCop.load-pre-releases": true` to the settings and you will get the pre-releases automatically 💪

**Comment by jwikman** [comment]
Cool @StefanMaron !

I just updated the extension and configured this - but how do I know if it works? 😉

I didn't see any new "Downloaded BC DLL" dialogue, not even after restart. And if I execute "BC: Download Linter cop" nothing happens either (from what I can see at least)

**Comment by StefanMaron** [comment]
Normally a dialog should show up. You can check the version of the dll in the file details. 
I will think about a better way, maybe an indicator somewhere to show the current file version

**Comment by jwikman** [comment]
I got dll v0.21.9.0 - Where do I find the current release and prerelease version in the repo?

**Comment by StefanMaron** [comment]
You will get an overview of all releases by clicking here on `Releases`:
![image](https://user-images.githubusercontent.com/24838311/143592694-59499639-60ed-4068-991e-3733c7a349e3.png)

**Comment by jwikman** [comment]
Ofcourse, where else! 😀

Well done!

Case closed, have a beer and a super weekend!
