### ISSUE TITLE
LC0013 - Update warning message to "should be set explicitly."

### ISSUE THREAD

**Issue by rvanbekkum** [StefanMaron/BusinessCentral.LinterCop#97]
See https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/92.

> But I agree, an explicit NotBlank = false should also satisfy the rule.

It would be good to change the text to:
"The NotBlank property should be set explicitly for tables with a single-field primary key."
to avoid confusion.

**Comment by StefanMaron** [comment]
This should be fixed with the latest version.
