### ISSUE TITLE
LC0011 Only apply rule to Enums and Interfaces when runtime 7.0 or greater is used in the app

### ISSUE THREAD

**Issue by rvanbekkum** [StefanMaron/BusinessCentral.LinterCop#98]
The `Access` property is only available for `Enum` and `Interface` objects for runtime 7.0 and greater.
Accordingly we should have rule only apply for enums and interfaces when the runtime is set to 7.0 or greater, otherwise the rule should skip these object types.

**Comment by StefanMaron** [comment]
Available in pre-release v0.21.9
